### ISSUE TITLE
Stackdriver Profiling with Docker image created using Bazel

### ISSUE THREAD

**Issue by vishalgarg837** [bazelbuild/rules_docker#1049]
I am trying to do Stackdriver Profiling with Docker image created using Bazel: https://cloud.google.com/profiler/docs/profiling-java

My BUILD file:

### Scheduler image
java_image(
    name = "dummy_image",
    main_class = "MainClass",
    runtime_deps = [":main"],
)

# Includes the gcloud installation archive
container_layer(
    name = "gcloud-layer",
    tars = [
        "@gcloud_archive//file",
    ],
)

container_image(
    name = "dummy_with_creation_time",
    base = ":dummy_image",
    stamp = True,
    layers = [
        ":gcloud-layer",
    ],
)

# Bootstrap the container image by installing some additional
# packages and running some post install steps
container_run_and_commit(
    name = "gcloud_install",
    commands = [
        # Finalize the gcloud installation
        "/google-cloud-sdk/install.sh -q",
        # Add the gcloud binaries to PATH
        "echo 'source /google-cloud-sdk/path.bash.inc' >> ~/.bashrc",
        "apt-get update",
        "mkdir -p /opt/cprof && \
             wget -q -O- https://storage.googleapis.com/cloud-profiler/java/latest/profiler_java_agent.tar.gz \
             | tar xzv -C /opt/cprof",
        # Install kubernetes as a component of gcloud
        "/google-cloud-sdk/bin/gcloud components install --quiet kubectl",
    ],
    image = ":dummy_with_creation_time.tar",
)

container_push(
    name = "push_container",
    format = "Docker",
    image = ":gcloud_install_commit.tar",
    registry = "gcr.io",
    repository = "testing",
    tag = "latest",
)

It's taking huge time to push image. How can i make it work?

**Comment by vishalgarg837** [comment]
@xingao267 Can you please help here?

**Comment by xingao267** [comment]
@nlopezgi

**Comment by nlopezgi** [comment]
HI @vishalgarg837 ,
Thanks for creating this issue. How long is it taking to push? So is the push failing at some point or is it just taking a long time? If its just taking a long time then there might be no problem here other than you just creating a really big image. So how big is the image once it's ready to be pushed? If it's really big, then you should expect it to take a long time to push. 
As for optimizing the image to make it smaller doing things like cleaning up files that your installation might leave behind might help.
Closing for now. Please let me know if you think there is any reason to keep this issue open.

**Comment by vishalgarg837** [comment]
Hi @nlopezgi When i am creating docker image without `container_run_and_commit` rule then it's taking 10-20 seconds but when i use `container_run_and_commit` rule then i waited for 15 minutes but it didn't complete. So i am not sure why is it happening?

**Comment by nlopezgi** [comment]
so what were you using to create the image w/o `container_run_and_commit`? Were you producing an image with the same contents that took 10-20 seconds or was it just a bare image that when you added all the content in your `run_and_commit` rule then it takes a long time to push? If that's the case, then its likely because what you are doing in `run_and_commit` is making the image huge. 

> i waited for 15 minutes but it didn't complete. So i am not sure why is it happening?
Did it error out after the 15 minutes, or was it still going?
How big is the image in your local registry if you load the tar?

**Comment by vishalgarg837** [comment]
@nlopezgi It's the same image which took 10-15 seconds. 
No, It didn't error out, it was still in-progress, i just stopped after 15 minutes as that much time is not acceptable. Image size is ~250 MB. You can see in issue what i am trying to do in `container_run_and_commit` rule, i don't believe it should cause so much performance decrease.

**Comment by nlopezgi** [comment]
so what were you using to create the image w/o container_run_and_commit?

**Comment by vishalgarg837** [comment]
@nlopezgi I tried with `container_run_and_commit` and it didn't complete in 15 minutes and i stopped. When i tried without `container_run_and_commit` then it just took 10-20 seconds. Content was same both time.

**Comment by nlopezgi** [comment]
so you're comparing what happens when you had a slim image that had no content with what happens when you added a bunch of content with `run_and_commit`? I'm not saying its ok for this to take 15 minutes+, but that's not really a fair comparison, as its not the same image. Or am I misunderstanding what you are saying. To be specific, which image took 10-20 seconds (and please try to be specific, dont say, the same one without `container_run_and_commit`, because that does not make sense, its not the same image if you did not run the commands to install gcloud in there in some way). 
Let me be specific about what I think might be happening that bloats your image:
You are running apt-get update, wget and an install script. These operations might be bloating up the image making it much larger than the one before you ran the scripts, so its not really fair to say these are the same images in any way.
It would be perhaps better to do a `run_and_extract` to get only the results of the installation process, to get the profiler_java_agent.tar.gz via a repo rule and pass it into the container via files attr, and, ideally, avoid running apt-get update. Now, if you do that, you might get a slimmer image that is easier to push. But I'm not sure how we can help if the image you are pushing is too large, or you have a bad connection to the registry (i.e., have you tried pushing to a local registry to see if that is faster?)
