### ISSUE TITLE
legacy_run_behavior has no effect on cc_image rules 

### ISSUE THREAD

**Issue by timford** [bazelbuild/rules_docker#1085]
According to https://github.com/bazelbuild/rules_docker#container_image-1, the `legacy_run_behavior` attribute defaults to `False` when using `<lang>_image` rules. This suggests it could be set to `True`, but doing so appears to have no effect. Tested on v0.9.0.

Example:
```
cc_image(
    name = "quickstore_microservice_mako_image",
    args = ["--addr=0.0.0.0:9813"],
    binary = ":quickstore_microservice_mako",
    legacy_run_behavior = True,
)
```

I also tried to set the same attribute on a custom base, as a potential workaround:
```
container_image(
    name = "base_image",
    base = "@cc_image_base//image",
    legacy_run_behavior = True,
)

cc_image(
    name = "quickstore_microservice_mako_image",
    args = ["--addr=0.0.0.0:9813"],
    binary = ":quickstore_microservice_mako",
    base = ":base_image",
)
```

That had no effect (I believe by design).

**Comment by smukherj1** [comment]
Hi @timford,

Thanks for opening the issue. Could you please clarify what you meant by `That had no effect (I believe by design).`. 

Note that as per the documentation of [legacy_run_behavior](https://github.com/bazelbuild/rules_docker#container_image-1), it's only supposed to affect the behavior of `bazel run` on a `container_image` target. When set to `False`, `bazel run` will also invoke `docker run` on the built container.` When set to `True`, `bazel run` will only make docker load the container but not run it. When you say it had no effect, did you mean when `legacy_run_behavior` was set to `True`, you noticed `docker run` being invoked on the built container when you ran `bazel run` on the image target?

**Comment by timford** [comment]
Sorry for the delay, and thanks for the response.

> did you mean whenlegacy_run_behaviorwas set toTrue, you noticed docker runbeing invoked on the built container when you ranbazel run` on the image target?

Correct. `cc_image` does not seem to support the `legacy_run_behavior` flag. I could find no way to create a `cc_image` that will load the image, but not try to run it, when doing `bazel run`. 

The language used in the documentation of `legacy_run_behavior` is "Note that it defaults to False when using <lang>_image rules." This is suggestive that the default behavior could be overridden by setting it to `True`.
