### ISSUE TITLE
simple py3_image builds on linux but fails on osx

### ISSUE THREAD

**Issue by cdg720** [bazelbuild/rules_docker#1094]
WORKSPACE
```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "io_bazel_rules_docker",
    sha256 = "e513c0ac6534810eb7a14bf025a0f159726753f97f74ab7863c650d26e01d677",
    strip_prefix = "rules_docker-0.9.0",
    urls = ["https://github.com/bazelbuild/rules_docker/archive/v0.9.0.tar.gz"],
)

load(
    "@io_bazel_rules_docker//repositories:repositories.bzl",
    container_repositories = "repositories",
)

container_repositories()

load(
    "@io_bazel_rules_docker//python3:image.bzl",
    _py_image_repos = "repositories",
)

_py_image_repos()
```

foo/BUILD
```
load("@io_bazel_rules_docker//python3:image.bzl", "py3_image")

py3_image(
    name = "hello_world",
    srcs = ["hello_world.py"],
)
```

foo/hello_world.py
```
print("Hello World!")
```

```
$ bazel run -c opt foo:hello_world
```
prints "Hello World!" on a linux machine (gcp cloud shell). But it fails with "OSError: [Errno 2] No such file or directory: '/usr/bin/python3'" on a mac.

Is the failure on OSX expected?

**Comment by smukherj1** [comment]
This is a follow up to #1087 & #1093. As you indicated in the comment [here](https://github.com/bazelbuild/rules_docker/issues/1087#issuecomment-521665210), your OSX issue happens because your python3 executable on your OSX machine isn't installed at `/usr/bin/python3`. Please either create a symlink from `/usr/bin/python3` on your OSX machine to the python3 binary or use the toolchain methodology indicated in #1087 & #1093.

Also, please avoid opening a new issue for the same problem. If a different repo owner ends up investigating, they may end up redoing part of the investigation work already done to debug the issue. Please re-open the existing issue or comment on it if you still need help.
