### ISSUE TITLE
container_push skip tag if sha256 exists

### ISSUE THREAD

**Issue by prestonvanloon** [bazelbuild/rules_docker#1106]
Context: https://groups.google.com/d/msg/bazel-discuss/UW3tDLHnKmo/xbreLVCOGAAJ

Is there some way to skip container_push if the docker image digest is already on the remote and already has a tag? The issue is that using the git commit hash in the image tag will push new tags even if the image has not changed. We have some digests with dozens of tags and would like to prevent pipeline triggers on new tags when there is nothing changed.

**Comment by smukherj1** [comment]
Hi @prestonvanloon,

Thanks for opening the issue. As far as I can tell, `container_push` will always re-tag the image if the specified tag is different even if the digest is unchanged. We are open to a contribution that adds a boolean attribute to `container_push` which would skip tagging the image if the digest is unchanged. Also, note that we are currently in the process of migrating our rules from using the python containerregistry library to the Go containerregistry library. So if you do decide to implement this feature, I would suggest doing it for [new_container_push](https://github.com/bazelbuild/rules_docker#new_container_push) instead of `container_push`. Some important pointers:
1. Update the list of attributes accepted by the `new_container_push` rule [here](https://github.com/bazelbuild/rules_docker/blob/8650f276d214e84e43c1253bd839b838303d4197/container/new_push.bzl#L167). The attribute should default to false for backwards compatibility.
2. Modify this [list](https://github.com/bazelbuild/rules_docker/blob/8650f276d214e84e43c1253bd839b838303d4197/container/new_push.bzl#L40) to add a flag if the new attribute is set.
3. Add support for the new flag in the pusher Go binary [here](https://github.com/bazelbuild/rules_docker/blob/8650f276d214e84e43c1253bd839b838303d4197/container/go/cmd/pusher/pusher.go). The logic that skips the upload if the digest is unchanged would probably go just before the line [here](https://github.com/bazelbuild/rules_docker/blob/8650f276d214e84e43c1253bd839b838303d4197/container/go/cmd/pusher/pusher.go#L138).

**Comment by zbarahal** [comment]
@prestonvanloon if you have time can you take a pass at the linked PR and make sure it addresses your use case.

**Comment by prestonvanloon** [comment]
@zbarahal Thanks for quick resolution. The new container push is not backwards compatible so using new container push as a drop in with docker_push doesn't work.

I'll wait until the migration is complete I suppose. The big issue is that new container doesn't support bundle which is my main use case.

**Comment by smukherj1** [comment]
#1118 makes the new pusher a drop in replacement for the old pusher. Note that the Go pusher/digester produce different digests for the same image vs the python pusher/digester because it formats the image manifest slightly differently. The Go container pusher currently has a couple of known issues that will be fixed by #1123 (more details in the description of that PR).
