### ISSUE TITLE
unable to pull mysql image successfully

### ISSUE THREAD

**Issue by jmhodges** [bazelbuild/rules_docker#1125]
I've tried to download the mysql image at sha256:1a121f2e7590f949b9ede7809395f209dd9910e331e8372e6682ba4bebcc020b that had successfully worked on earlier versions. I'm on macOS and bazel 0.29.0.

I have a reproduction that you can use for this ticket in branch `docker_mysql` in https://github.com/jmhodges/bazel_bugs ([branch in the web UI](https://github.com/jmhodges/bazel_bugs/tree/docker_mysql)). I've set it up to work like item 3 below. You can reproduce it by running `bazel run //dockertest:dockertest`.

On v0.9.0 and HEAD (165cd95365684f5fa1f29abc71cf1006e06c581a), there are different errors.

1. On v0.9.0 with `container_pull`, the sha256 of the image downloaded doesn't match the one asked for in `digest`. The error is similar to 3's.

2. On v0.9.0 with `new_container_pull`, the `docker load` step fails on an "invalid diffID for layer 2". The sha256 requested for layer 2 is correct, but the 3rd layer ("layer 2") actually loaded is layer 10. This is because the files on disk are, in ASCII order, "0.tar.gz.nogz", "1.tar.gz.nogz", and then "10.tar.gz.nogz". To load these layers in the correct order, a numeric sort on the prefix has to be used by something (I'm not sure what) instead of the ASCII sort it does.

3. On HEAD with both `new_container_pull` and `container_pull`, the error is "SHA256 of the image specified does not match SHA256 of the pulled image". The expected digest (the one entered into `digest` in new_container_pull) doesn't match what is downloaded somehow.

3. On HEAD with `new_container_pull` and using the latest `puller` in HEAD, the error is that the `digest` file doesn't exist in `external/mysql/image` when `cat` is run. (I imagine something similar will happen with `container_pull` but this was as long as I could spend on the bug)

**Comment by jmhodges** [comment]
Broke out some of the errors to be more clear and complete.

**Comment by nlopezgi** [comment]
Alex will try to repro and report findings.

**Comment by alex1545** [comment]
Hi @jmhodges,
You are running into this issue because the `sha256:1a121f2e7590f949b9ede7809395f209dd9910e331e8372e6682ba4bebcc020b` that you pin to points to a manifest list (not an actual docker image).

Running 
```
docker manifest inspect mysql@sha256:1a121f2e7590f949b9ede7809395f209dd9910e331e8372e6682ba4bebcc020b
```
gives
```
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 2621,
         "digest": "sha256:2bd4665d9c5ecad61f7ceff82f82e6470c4686b9ec0fd986b84012861506c722",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      }
   ]
}
```
As you can see by the media type, this is a manifest list that points to a single image with `sha256:2bd4665d9c5ecad61f7ceff82f82e6470c4686b9ec0fd986b84012861506c722`. So you just need to pin to that sha instead.

It used to work for you before because at one point we disallowed the autoresolution to a specific image given a manifest list in favor of having the puller pull the image with the exact sha specified. You can read through issue #714 for more details if you are interested.

I hope this resolves your issues once you pin to the actual image being pulled.

**Comment by smukherj1** [comment]
Also, 

> On v0.9.0 with new_container_pull, the docker load step fails on an "invalid diffID for layer 2". The sha256 requested for layer 2 is correct, but the 3rd layer ("layer 2") actually loaded is layer 10. This is because the files on disk are, in ASCII order, "0.tar.gz.nogz", "1.tar.gz.nogz", and then "10.tar.gz.nogz". To load these layers in the correct order, a numeric sort on the prefix has to be used by something (I'm not sure what) instead of the ASCII sort it does.

is a legitimate issue with the Go puller that I'll look into.

**Comment by jmhodges** [comment]
Oh man, thanks!

Would you like a separate ticket for that ASCII sort bug?

**Comment by smukherj1** [comment]
> Oh man, thanks!
> 
> Would you like a separate ticket for that ASCII sort bug?

That would be great! Thanks!

**Comment by jmhodges** [comment]
Done! https://github.com/bazelbuild/rules_docker/issues/1127

I'll close this up

**Comment by jmhodges** [comment]
I do have one last question: stackoverflow and other places say the correct way to get the digest of an image is with:

`docker inspect --format='{{index .RepoDigests 0}}' $IMAGE`

but doing that on the tags I got this from (`mysql:5.7.27`) gets what you say is the wrong answer.

I'm clearly missing something obvious. Do you know what it is?

```
$ docker inspect --format='{{index .RepoDigests 0}}' mysql:5.7.27
[mysql@sha256:1a121f2e7590f949b9ede7809395f209dd9910e331e8372e6682ba4bebcc020b]
```

**Comment by jmhodges** [comment]
(The same sha256 is in the output of `docker images --digests`)

**Comment by jmhodges** [comment]
And my docker client (19.03.1) claims I'd need to turn on experimental features if I wanted to use `docker manifest inspect`. Is there a possibility that rules_docker is being too futuristic?

**Comment by alex1545** [comment]
Yes, your finding from stackoverflow is correct.
The main concept to understand here is the [manifest list](https://docs.docker.com/registry/spec/manifest-v2-2/#manifest-list). A manifest list is a special type of image that isn't your regular image that you can spin containers from, but rather a collection of pointers to other images. When you pull a manifest list, it automatically resolves and pulls the single image you need (usually based on your OS and arch). Hence, the manifest list can be treated as a regular image (because of this automatic resolution) and it has its own digest, which in our case is `sha256:1a121f2e7590f949b9ede7809395f209dd9910e331e8372e6682ba4bebcc020b`. This manifest list also has the tag `5.7.27`, which is why `docker inspect --format='{{index .RepoDigests 0}}' mysql:5.7.27` gives you the output you didn't expect.

You can also confirm this by pulling the image by both digests `1a121f2e7590f949b9ede7809395f209dd9910e331e8372e6682ba4bebcc020b` and `2bd4665d9c5ecad61f7ceff82f82e6470c4686b9ec0fd986b84012861506c722` and checking both images IDs (with `docker images`). You will see that you get the same image.

And yes, `docker manifest inspect` is an experimental feature and I have no idea why especially given that manifest list were introduced a few years ago. I didn't completely understand what you meant by
> Is there a possibility that rules_docker is being too futuristic or not user-friendly enough?

But if you would like to get the behaviour you were getting before, you can simply pull your image by tag like so:
```
container_pull(
    name = "mysql",
    registry = "index.docker.io",
    repository = "library/mysql",
    tag = "5.7.27",
)
```
However you are risking to be pulling different images if that tag moves to a different image.
