### ISSUE TITLE
files added via `tars` attribute of `container_image` will not override files in the base image

### ISSUE THREAD

**Issue by bbarnes52** [bazelbuild/rules_docker#1165]
This might be working as intended, but it seems like an unusual convention to me. For example, if I do:
```
container_image(
    name = foo,
    tars = [:target],
    # Other attributes omitted for brevity
)

pkg_tar(
    name = target,
    srcs = :somefilegroup,
    package_dir = /etc,
)

filegroup(
    name = somefilegroup,
    srcs = [resolv.conf],
 )
```

The `resolv.conf` that winds up in my image is the one in the base image, not the one in my tar. If I'm overriding a file in the base image, I think it's safe to assume I'm doing so intentionally.

**Comment by alex1545** [comment]
Hi @bbarnes52,

I was able to reproduce your scenario. However, files added via `tars` attr of `container_image` do overwrite files in the base image.
The specific problem that you encounter is due to the fact that you try to overwrite a special file (being `resolv.conf`) that is managed by Docker itself. You probably will not be able to perform an equivalent operation with a Dockerfile either.

You should learn more about how to properly configure a container DNS [here](https://docs.docker.com/v17.09/engine/userguide/networking/default_network/configure-dns/).
