### ISSUE TITLE
bazel push instead of bazel run

### ISSUE THREAD

**Issue by boseabhishek** [bazelbuild/rules_docker#1174]
Why do we use bazel run to push a container image to Docker Registry rather than something like bazel push? (sorry I am new to Bazel)

**Comment by boseabhishek** [comment]
I think bazel run is quite a generic command and it depends upon which action it is invoking. That is the reason bazel run is used.

**Comment by smukherj1** [comment]
Hi @boseabhishek,

Your assessment is correct. The support commands in Bazel are [here](https://docs.bazel.build/versions/master/command-line-reference.html#commands).

Bazel rules like rules_docker provide a way to use the existing set of commands in Bazel for domain specific purposes. `bazel build` is used to build targets, `bazel run` is used to run executables built with `bazel build`. So the `container_push` rule builds an executable that can push a docker image. So if you `bazel build` a container_push target, you get this executable. The executable is run when you use `bazel run` which actually pushes the image.

A follow up question might be why not push the image in `bazel build` instead of requiring the use of `bazel run`. This is because pushing containers is a non-hermetic action whereas bazel build actions are supposed to be hermetic to be reproducible.
