### ISSUE TITLE
Using a target instead of a path in docker_toolchain

### ISSUE THREAD

**Issue by Faqa** [bazelbuild/rules_docker#1255]
Hi,

I'm wondering if there's some reason the docker_toolchain code doesn't allow for pulling the docker client itself from another WORKSPACE target. At my job, we already have bazel targets using Docker, and they all rely on a static version of the docker binary dowloaded like so:

```
http_archive(
    name = "docker_client_linux",
    urls = ["https://download.docker.com/linux/static/stable/x86_64/docker-%s.tgz" % DOCKER_VERSION],
    sha256 = "183e10448f0c3a0dc82c9d504c5280c29527b89af0fc71cb27115d684b26c8bd",
    strip_prefix = "docker",
    build_file_content = "exports_files(['docker'])",
)

http_archive(
    name = "docker_client_darwin",
    urls = ["https://download.docker.com/mac/static/stable/x86_64/docker-%s.tgz" % DOCKER_VERSION],
    sha256 = "1c752af399fd281e1969a3ff367b2501bf8131b70573c118763aa2825364f4ef",
    strip_prefix = "docker",
    build_file_content = "exports_files(['docker'])",
)
```

We find this is quite helpful for making sure everyone is using the same version of the docker client "out of the box". Unless I'm missing something about Bazel toolchains, there doesn't seem to be a way to feed a Bazel target to `tool_path`, nor to specify a remote URL for it. If so, would you be open to a PR that adds such behavior?

**Comment by alex1545** [comment]
Hi @Faqa,

No, there is no specific reason as to why the `docker_toolchain` rule defines the `tool_path` attribute as a string and it being the only option. The `tool_path` attribute being a string allows specifying the path to the `docker` tool and this is what we needed so far.

And yes, we will be happy to review a PR that adds to ability to specify a Bazel target for the `docker` tool instead of the string for the `tool_path`. We have actually implemented such behaviour in [rules_k8s](https://github.com/bazelbuild/rules_k8s) for the [kubectl_toolchain](https://github.com/bazelbuild/rules_k8s/blob/master/toolchains/kubectl/kubectl_toolchain.bzl#L37-L49). You can start by looking at that toolchain definition and let me know if you have further questions.
