### ISSUE TITLE
container_load regression

### ISSUE THREAD

**Issue by yitaosun** [bazelbuild/rules_docker#1275]
During a recent attempt to upgrade rules_docker from v0.5.1 to v0.7.0, we observed a regression in our CI when fetching `container_load` image dependencies. What used to take ~15s now takes >3minutes. Although the regression timing is subjective, it is [reproducible](https://github.com/yitaosun/repro/tree/rules_docker/rules_docker). A little digging indicates the the regression is actually caused by the upgrade to Google Container Registry (e5785ceaef4eb7e0cc28bdb909fd1b10d5b991c3). The regression is improved by v0.12.0, but it still takes longer than v0.5.1.

My bazel version is 0.24.1.

```
bazel version
Build label: 0.24.1-2.6
Build target: bazel-out/k8-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Aug 21 20:43:32 2019 (1566420212)
Build timestamp: 1566420212
Build timestamp as int: 1566420212
```

**Comment by alex1545** [comment]
We recommend that you use the latest v0.12.1 release. We have recently migrated rules_docker to use [go-containerregistry](https://github.com/google/go-containerregistry) instead of the python based [containerregistry](https://github.com/google/containerregistry). See #580 for more details.

We are currently unable to comment on what exactly happened when updating the python containerregistry from v0.0.32 to v0.0.34.

When reproducing your issue, it takes me ~30s to build the `container_pull` target from scratch. But note that this includes fetching all repo dependencies. Having the repo dependencies fetched, it takes ~8s to build the `container_pull` target.

If you feel things are still slow for you and this can be improved, then you can look at the new loader logic [here](https://github.com/bazelbuild/rules_docker/blob/master/container/go/cmd/loader/loader.go). We are currently not allocating time for new feature development, but are happy to accept contributions.

**Comment by nlopezgi** [comment]
Closing as there is no action to take atm, but please let me know to reopen for any reason.
