### ISSUE TITLE
Deploy with pusher is not incremental

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/rules_docker#128]
We have to update to the latest docker rules for https://github.com/bazelbuild/continuous-integration and tried to switch to docker_push (actually the one in contrib) but the docker push is super slow, way slower than `docker load` and `gcloud docker push`. It seems like the push is non incremental because it is taking a long time.

Our git diff:

```
$ git diff HEAD~ BUILD
diff --git a/gcr/BUILD b/gcr/BUILD
index 581da4b..f42c670 100644
--- a/gcr/BUILD
+++ b/gcr/BUILD
@@ -1,20 +1,35 @@
-load(":docker_push.bzl", "docker_push")
+load(
+    "@io_bazel_rules_docker//docker:docker.bzl",
+    "docker_bundle",
+)
+load(
+    "@io_bazel_rules_docker//docker/contrib:push-all.bzl",
+    "docker_push",
+)
+
+docker_bundle(
+    name = "prod-bundle",
+    images = {
+        "gcr.io/bazel-public/jenkins-master:latest": "//jenkins:jenkins",
+        "gcr.io/bazel-public/deploy-slave:latest": "//jenkins:deploy.docker",
+        "gcr.io/bazel-public/sync-gerrit-github:latest": "//gerrit-github-sync:gerrit-github-sync",
+    },
+)
 
 docker_push(
     name = "deploy",
+    bundle = ":prod-bundle",
+)
+
+docker_bundle(
+    name = "staging-bundle",
     images = {
-        "//jenkins:jenkins": "jenkins-master",
-        "//jenkins:deploy.docker": "deploy-slave",
-        "//gerrit-github-sync:gerrit-github-sync": "sync-gerrit-github",
+        "gcr.io/bazel-public/jenkins-master-staging:latest": "//jenkins:jenkins-staging",
+        "gcr.io/bazel-public/deploy-slave-staging:latest": "//jenkins:deploy-staging.docker",
     },
-    repository = "gcr.io/bazel-public",
 )
 
 docker_push(
     name = "deploy-staging",
-    images = {
-        "//jenkins:jenkins-staging": "jenkins-master-staging",
-        "//jenkins:deploy-staging.docker": "deploy-slave-staging",
-    },
-    repository = "gcr.io/bazel-public",
+    bundle = ":staging-bundle",
 )
```

Time for bazel run //gcr:deploy-staging with 0 change: 2m37s, vs 21s with our previous use of gcloud docker push...

**Comment by damienmg** [comment]
(also the docker_push is not showing any progress, just stalled)

**Comment by mattmoor** [comment]
I don't see a `docker_pull` in your diff, which almost certainly means you are pushing with a legacy base (do you see a warning?).

**Comment by damienmg** [comment]
Right I see warnings. let me try to use docker_import.

Also can pusher print out progress messages?

**Comment by damienmg** [comment]
Why is `layers` attribute needed for [docker_import](https://github.com/bazelbuild/rules_docker#docker_import) ?

**Comment by damienmg** [comment]
Sorry that's me mireading the doc.

**Comment by damienmg** [comment]
Actually that still stands, why docker_import cannot just take a docker save tarball?

**Comment by damienmg** [comment]
'.../layer.tar' does not produce any docker_import_ layers files (expected .tar.gz or .tgz). Since this rule was created by the macro 'docker_import' [...]

That start to be a lot of preprocessing to feed it a docker save image..

**Comment by mattmoor** [comment]
> why docker_import cannot just take a docker save tarball?

@damienmg because I'm not smart enough to write a Skylark rule that outputs a variable number of things.  If such a thing is possible, I welcome guidance on how to do it.  Bear in mind, this is a `BUILD` rule, not a `WORKSPACE` repository rule.

> That start to be a lot of preprocessing to feed it a docker save image

You dodged my `docker_pull` question, I still have no clue why you are starting from `docker save` :)

If you must start from `docker save`, then I'd recommend writing a `repository_rule` like `docker_pull` that uses `docker_image.FromTarball` instead of `docker_image.FromRegistry`.  This should entail:
1. a small CL in the mono-repo to add a tool to `google/containerregistry` (start from a copy of fast_puller.py)
1. a release of `google/containerregistry` (we're due for one anyways to pull in OCI support into `rules_docker`)
1. a small change to `rules_docker` to bump the dep version and create a `docker_load`(?) repository rule that imports a tarball.

> Also can pusher print out progress messages?

@jmillikin-stripe has a PR that adds logging to the library's tools.  IIRC he's waiting on @jonjohnsonjr

**Comment by damienmg** [comment]
> > why docker_import cannot just take a docker save tarball?
>
> @damienmg because I'm not smart enough to write a Skylark rule that outputs a variable number of things. If such a thing is possible, I welcome guidance on how to do it. Bear in mind, this is a BUILD rule, not a WORKSPACE repository rule.

:) I see

The problem is that we depends on Ubuntu image for continuous-integration: https://github.com/bazelbuild/continuous-integration/blob/master/base/Dockerfile.ubuntu-wily-amd64 (and other docker file in that directory). There is no big issue with using other thing that ubuntu except that it would be long to switch over, so we have to rely on docker build for now.

**Comment by jmillikin-stripe** [comment]
@damienmg I believe the slowness in your push is caused by compression in push.par, which is slow. Moving layer compression to the build step should help. Can you try running with my two PRs (https://github.com/bazelbuild/rules_docker/pull/117, https://github.com/google/containerregistry/pull/13) to see if that helps the push performance?

If so, then perhaps you could help @mattmoor get them merged in, or see if he'll accept CLs that do something similar with a non-Docker-compatible format.

> because I'm not smart enough to write a Skylark rule that outputs a variable number of things. If such a thing is possible, I welcome guidance on how to do it. Bear in mind, this is a BUILD rule, not a WORKSPACE repository rule.

I can help you with this, if you can put a rough draft of what you want in a Gist. BUILD rules can generate any number of files as long as the output list can be calculated before running the build.

**Comment by damienmg** [comment]
FTR I worked around it: https://bazel-review.googlesource.com/c/continuous-integration/+/16351

So we now use a docker_pull rule that use docker to build. I tried going the distroless road but it gets harder now (would have probably be easier if we had that from the beginnning since at the beginning we were using a list of debs and jessie as base image).

I can definitely look at the docker PR.

**Comment by mattmoor** [comment]
> as long as the output list can be calculated before running the build

That's exactly the problem, until we crack the tarball we have no clue what our output count will be.  This can be done in a repository rule (WORKSPACE), but not in a BUILD rule, thus my suggestion.

**Comment by mattmoor** [comment]
@damienmg If this is no longer a problem, can you close?

**Comment by damienmg** [comment]
Indeed it's fixed, maybe we should contribute the docker_pull back here in contrib.

**Comment by mattmoor** [comment]
@damienmg Perhaps, I left some comments on the Gerrit review.
