### ISSUE TITLE
Weird empty layer is generated sometimes

### ISSUE THREAD

**Issue by jonjohnsonjr** [bazelbuild/rules_docker#1392]
I've seen this for [gcr.io/distroless/static:nonroot](https://github.com/GoogleContainerTools/distroless/blob/b54513ef989c81d68cb27d9c7958697e2fedd2c4/base/base.bzl#L76-L82) and also in the [kubernetes container image promoter](https://github.com/kubernetes-sigs/k8s-container-image-promoter/blob/b7378030785b6cf6da2cde095eb68ff06483712b/test-e2e/cip/BUILD.bazel#L86-L89).

The layer is 10240 bytes of \0:
```
$ crane blob gcr.io/distroless/static@sha256:3c2cba919283a210665e480bcbf943eaaf4ed87a83f02e81bb286b8bdead0e75 | gunzip | wc -c
10240
 
$ crane blob gcr.io/distroless/static@sha256:3c2cba919283a210665e480bcbf943eaaf4ed87a83f02e81bb286b8bdead0e75 | gunzip | xxd
00000000: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000010: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000020: 0000 0000 0000 0000 0000 0000 0000 0000  ................
<snipped>
```

But it's compressed differently in certain contexts, sometimes producing `sha256:85cea451eec057fa7e734548ca3ba6d779ed5836a3f9de14b8394575ef0d7d8e` and other times `sha256:3c2cba919283a210665e480bcbf943eaaf4ed87a83f02e81bb286b8bdead0e75`.

A potential clue is that [python's tar library](https://docs.python.org/3/library/tarfile.html#tarfile.open) uses a default buffer size of 10240 bytes: 

> `tarfile.open(name=None, mode='r', fileobj=None, bufsize=10240, **kwargs)`

**Comment by smukherj1** [comment]
Discussed this offline but posting here for posterity. The empty layers seem to be created for metadata layers. While this is not ideal but it was determined to not be a problem/blocking in the issue that was being debugged while this discovery was made. So closing this for now because actually fixing this could have unintended consequences in applications that have come to depend on this non-standard behavior and will require careful analysis before rolling out the fix.
