### ISSUE TITLE
Clashing of Python and Docker workspace rules

### ISSUE THREAD

**Issue by mvukov** [bazelbuild/rules_docker#1404]
Hi, I am working with Bazel 1.2.1 and 2.0.

In my WORKSPACE file I have:
```
http_archive(
    name = "io_bazel_rules_docker",
    sha256 = "dc97fccceacd4c6be14e800b2a00693d5e8d07f69ee187babfd04a80a9f8e250",
    strip_prefix = "rules_docker-0.14.1",
    urls = ["https://github.com/bazelbuild/rules_docker/releases/download/v0.14.1/rules_docker-v0.14.1.tar.gz"],
)

http_archive(
    name = "rules_python",
    url = "https://github.com/bazelbuild/rules_python/archive/94677401bc56ed5d756f50b441a6a5c7f735a6d4.tar.gz",
    strip_prefix = "rules_python-94677401bc56ed5d756f50b441a6a5c7f735a6d4",
    sha256 = "acbd018f11355ead06b250b352e59824fbb9e77f4874d250d230138231182c1c",
)

# ...

# Python setup

load("@rules_python//python:repositories.bzl", "py_repositories")
load("@rules_python//python:pip.bzl", "pip_repositories")
load("@rules_python//python:pip.bzl", "pip3_import")
py_repositories()
pip_repositories()
pip3_import(
   name = "pip_deps",
   requirements = "//:requirements.txt",
)
load("@pip_deps//:requirements.bzl", "pip_install")
pip_install()

# Docker setup
load(
    "@io_bazel_rules_docker//repositories:repositories.bzl",
    container_repositories = "repositories",
)
container_repositories()

load(
    "@io_bazel_rules_docker//cc:image.bzl",
    _cc_image_repos = "repositories",
)

_cc_image_repos()

load("@io_bazel_rules_docker//repositories:deps.bzl", container_deps = "deps")
container_deps()

# ...

```

This setup works. At the moment I only build Docker images with cc binaries.

If I reorder Python setup and Docker setup, Bazel picks up some other requirements.txt file --  I guess from the Docker setup, that one is rather small, includes PyYAML etc. All in all, I cannot run some of my Python targets.

I will try to alias Python command imports, but wanted to let you know of the issue.

**Comment by mmikitka** [comment]
I am encountering the same problem, and the issue is that you have a `@pip_deps` repository target in your WORKSPACE that conflicts with the same `@pip_deps` repository target in rules_docker.

Renaming `pip_deps` to `container_deps` like you did, does not fix the problem because the rules_docker code references `@pip_deps`.

I think that a more project-scoped name is appropriate so rules_docker can play nice with other repos and user WORKSPACE files.

Since `container_` is often used as a prefix in the repo, I renamed `pip_deps` to `container_pip_deps`. Here is the PR: https://github.com/bazelbuild/rules_docker/pull/1576

**Comment by mvukov** [comment]
Cool, thanks for digging in. It's good that we now know the source of the conflict.
