### ISSUE TITLE
make variable support for docker pull.

### ISSUE THREAD

**Issue by hsyed** [bazelbuild/rules_docker#141]
make substitution is not working in registry and repository.

It should be supported for the same reasons that it is in `docker_build` and `docker_push`.

**Comment by mattmoor** [comment]
If the make facilities are available in that context, this should be pretty easy to add.  I'll try to find some time to knock this off.

**Comment by mattmoor** [comment]
Hmm.  I need [this method](https://docs.bazel.build/versions/master/skylark/lib/ctx.html#expand_make_variables) [here](https://docs.bazel.build/versions/master/skylark/lib/repository_ctx.html) in order to do this.

@damienmg Who owns this and can (hopefully) correct my understanding?

For the record, all I'm trying to do is add a tiny bit of logic like [this](https://github.com/bazelbuild/rules_docker/blob/master/docker/push.bzl#L59-L60) to [here](https://github.com/bazelbuild/rules_docker/blob/master/docker/pull.bzl#L54).

**Comment by damienmg** [comment]
https://github.com/bazelbuild/bazel/issues/3736 <-- Filed on the bazel side.

**Comment by nlopezgi** [comment]
is this still an issue? please reopen if so.
