### ISSUE TITLE
container_bundle duplicates layer content for identical layers

### ISSUE THREAD

**Issue by copymark** [bazelbuild/rules_docker#1420]
Hi,

when you create a tar file that can be loaded by "docker load -i file.tar" with container_bundle and combine images that share identical layers, then the contents of each layer (layer.tar, json and VERSION file) are duplicated inside the tar.
This results in heavily increased file size.

### **Steps to reproduce:**
1. Use very simple example **WORKSPACE** from the readme
```
workspace(name = "testcontainerbundle")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "io_bazel_rules_docker",
    sha256 = "dc97fccceacd4c6be14e800b2a00693d5e8d07f69ee187babfd04a80a9f8e250",
    strip_prefix = "rules_docker-0.14.1",
    urls = ["https://github.com/bazelbuild/rules_docker/releases/download/v0.14.1/rules_docker-v0.14.1.tar.gz"],
)

load(
  "@io_bazel_rules_docker//repositories:repositories.bzl",
  container_repositories = "repositories",
)
container_repositories()

load("@io_bazel_rules_docker//repositories:deps.bzl", container_deps = "deps")

container_deps()

load(
    "@io_bazel_rules_docker//container:container.bzl",
    "container_pull",
)

container_pull(
  name = "java_base",
  registry = "gcr.io",
  repository = "distroless/java",
  digest = "sha256:65d23224482a20dedb62c94d258706f3949c02bd0522a97fee08d17ab38f1813"
)
```
2. Create the most simple container_bundle rule that includes the java base image with two different tags in your **BUILD** file:

```
load("@io_bazel_rules_docker//container:container.bzl", "container_bundle")

container_bundle(
    name = "bundle",
    images = {
        "gcr.io/foo/bar:bazz": "@java_base//image",
        "gcr.io/foo/bar:blah": "@java_base//image"
    }
)
```
3. Build the bundle with `bazel build //:bundle.tar`
4. Inspect the resulting tar with eg. 7Zip

![image](https://user-images.githubusercontent.com/5455170/74388983-202b6180-4dfd-11ea-957e-a90b123b48a4.png)

The native docker executable does not duplicate the layer contents.

**Comment by smukherj1** [comment]
So the way this works is `container_bundle` calls the `join_layers` Go binary [here](https://github.com/bazelbuild/rules_docker/blob/ddaae1d509be871d8d5287ec2aa1648ce19781a5/container/go/cmd/join_layers/join_layers.go) which loads the relevant images and writes them out in a single tarball. I think the optimization to not duplicate the layers would be best implemented in the tarball writer called by the `join_layers` binary [here](https://github.com/bazelbuild/rules_docker/blob/ddaae1d509be871d8d5287ec2aa1648ce19781a5/container/go/cmd/join_layers/join_layers.go#L111) and implemented [here](https://github.com/google/go-containerregistry/blob/379933c9c22b8ff1b396b5b7f4ec322d27f0a206/pkg/legacy/tarball/write.go#L193). @jonjohnsonjr do you agree with this fix being made in go-containerregistry instead of here?

If the idea of implementing this optimization in go-containerregistry is agreeable to @jonjohnsonjr, please feel free to send a PR contributing the same to go-containerregistry and I can help you with next steps on merging that change in rules_docker.

**Comment by copymark** [comment]
You are right. There already was an issue for that on go-containerregistry [https://github.com/google/go-containerregistry/issues/265](here). However it did not patch the legacy tarball package.
Why is the legacy version used anyways?

**Comment by smukherj1** [comment]
When the `join_layers` binary in rules_docker was implemented (September 2019 approximately), `docker save` produced the "legacy" format by default and thus for the tarball produced by rules_docker to look like the docker tarball, `join_layers` writes out the legacy format.

**Comment by jonjohnsonjr** [comment]
> do you agree with this fix being made in go-containerregistry instead of here?

Definitely! I'd happily take a PR.

**Comment by brian-brt** [comment]
I was getting ready to file my own bug before finding this one, so here's a more minimal self-contained reproduction I created if it helps anybody (works with the same WORKSPACE as the original description, but the container_pull isn't necessary):

```python
load("@io_bazel_rules_docker//container:container.bzl", "container_bundle", "container_image")

genrule(
    name = "make_empty_files",
    outs = [
        "file1",
        "file2",
    ],
    cmd = "touch $(OUTS)",
)

container_image(
    name = "base",
)

container_image(
    name = "derived1",
    base = ":base",
    files = ["file1"],
)

container_image(
    name = "derived2",
    base = ":base",
    files = ["file2"],
)

container_bundle(
    name = "bundle",
    images = {
        "example.com/foobar1": ":derived1",
        "example.com/foobar2": ":derived2",
    },
)
```

`tar tf bazel-bin/bundle.tar | sort | uniq -d` will print any duplicate files.
