### ISSUE TITLE
Support certificates similar to /etc/docker/certs.d/

### ISSUE THREAD

**Issue by Qinusty** [bazelbuild/rules_docker#1435]
Is it possible to use `container_pull` to pull images from a registry requiring certificates for authentication? When using the docker daemon, I am able to pull from the registry as my certificates are in `/etc/docker/certs.d/<registry>` but `container_pull` seems to fall over.

Can the toolchain detailed in https://github.com/bazelbuild/rules_docker#setup be configured to handle this use case?

**Comment by alex1545** [comment]
To use certificates for authentication, `container_pull` requires an additional setup that uses custom docker client config. You would need to specify the `client_config` attribute in your `docker_toolchain_configure` target as described in the [setup](https://github.com/bazelbuild/rules_docker#setup) section. Then check the [authentication](https://github.com/bazelbuild/rules_docker#authentication) section, which points to the [container_pull (Custom client configuration)](https://github.com/bazelbuild/rules_docker#container_pull-custom-client-configuration) for further instructions. 

For more background information on how this issue was originally resolved, check out #273 
Closing for now, but let me know if you still run into issues.
