### ISSUE TITLE
Having a container_pull call in the WORKSPACE breaks Windows completely.

### ISSUE THREAD

**Issue by PaulSonOfLars** [bazelbuild/rules_docker#1438]
`container_pull` is essential to the rules_docker usage - as seen in the Readme.

However, since there is no windows puller, this rule cannot be used on a windows machine, failing with some obscure error about not being able to run the linux puller, which is the default puller. This means that projects using `rules_docker` are essentially completely broken when it comes to cross-platform, since the WORKSPACE cannot be fully evaluated, meaning no other commands can be run.

I understand not being able to use RUN directives, since that requires calling into docker, and I could see issues arising from that - but I struggle to understand why the puller isn't supported. From what I can see, the linux and mac pullers are calling out to a go script, which doesn't seem to be too complex - am I missing something? In the least, would it be possible to make `container_pull` on windows a NOOP, perhaps with a warning? 

I'd be happy to open a PR to address some of these issues, if there is any interest (and I'm not completely off the mark with my understanding of the current state!)

As an aside - it looks like the `go_puller_{linux,darwin}` binaries are obtained via http - could they not be built locally instead?

**Comment by arjunkamp** [comment]
Hi,

I faced the same issue with ARM64 builds.  I built my own puller binaries, updated the local rules_docker/repositories/repositories.bzl to load those custom binaries, and and then tar/zipped a local rules_docker repo for inclusion by my target projects.  Which also means had to update those projects' rules_docker http_file path.

Agree it would be better if puller and loader were built on the spot instead of the binaries being pulled from a repo, since the target machine may not be linux/amd64.

Thanks,
Arjun

**Comment by PaulSonOfLars** [comment]
Glad to hear this is a problem for others too. 

@arjunkamp, do you happen to have a git repo with your changes available somewhere? Would love to pick through the diff and see if a generic solution can be obtained to solve both our uses cases.

**Comment by alex1545** [comment]
Hi @PaulSonOfLars and thank you for opening this issue.
Unfortunately, we don't have a CI setup for testing these rules against Windows. This brought rules_docker to the point where they are now definitely broken on Windows.

As to why the puller isn't supported, the answer is similar. There isn't much value in hosting a Windows puller if we don't currently test these rules on Windows. But in cases like yours (and as @arjunkamp mentioned), we recommend that you build your own puller, host it in a location accessible via the `http_file` target and maintain it for your own use case. Check this [comment](https://github.com/bazelbuild/rules_docker/issues/1155#issuecomment-532810855) for a detailed instruction on how this can be done.

That being said, we are happy to accept community contributions that improve rules_docker and add tests for the proposed changes.

And this is correct that the puller binaries are downloaded via the `http_file` target. Since the `container_pull` is a repository rule, its target cannot depend on a BUILD rule target, hence the puller binary cannot be built on the fly. See #1280 for a relevant discussion.

**Comment by PaulSonOfLars** [comment]
I see. This makes sense - I can see how bringing up windows support is a non-trivial effort, since all the tests would likely need fixing and extra windows edge cases need to be added.

The repository_rule not being able to depend on BUILD rule targets was something that I'd completely missed and not thought about - thanks for clarifying that.

Thank you for the detailed comment/explanation - this is very helpful! I'll see how this can be used in our use-case. I'll make sure to share open any issues and share bugfixes if I have anything to add.
