### ISSUE TITLE
download_pkg/install_pkg and deterministic builds

### ISSUE THREAD

**Issue by tjarjoura** [bazelbuild/rules_docker#1465]
So I recently discovered that the "debs" attribute on the container_image rule is deprecated, and it seems like (correct me if I'm wrong) download_pkg/install_pkg are the replacement. However, from what I can tell download_pkg does not work using snapshots like the dpkg_list rule (which would be passed into the old debs attribute), it simply runs "apt get" on whatever package string you give it. This presumably would download from a live server that is subject to changes instead of a snapshot which should never change. Doesn't this mean that the builds with the new rules are no longer deterministic? Is there any recommended way of getting around this? Is it possible to mix and match ie. use dpkg_list as an input to install_pkg? I'm sure I can just write my own rule but was wondering if there was already a supported solution.

Hopefully my question is clear, please let me know if there's any confusion. Thanks!

**Comment by alex1545** [comment]
Hi @tjarjoura.
Yes, this is correct that the `debs` attribute was deprecated from the `container_image` rule. This was done due to the fact that it only extracted the packages inside the image. It didn't install the packages themselves (as was expected by the users) because installation required additional steps that need to run a container (which `container_image` doesn't do).
Your understanding of `download_pkgs` is correct. If you use the output of your `download_pkgs` target directly in your `install_pkgs` target, you may run into non-deterministic builds for the reasons you mentioned. But to achieve deterministic builds, we use the `download_pkgs` rule to tar a collection of packages and save that as a snapshot (host the resulting tar on GCS for example). Then using the `http_file` rule we download that snapshot and feed it into the `installables_tar` attribute of the `install_pkgs` rule.

Please let me know if you need more help and whether you think this issue should still be opened.

**Comment by joeljeske** [comment]
@alex1545, could this be mentioned in the documentation with a clear best practice? I came to the issues looking for this discussion, because as @tjarjoura, I did not understand how determinism could be maintained in this approach. From my perspective, any official bazel rules should aim toward correct determinism. If that is not possible, it should clearly warn about the downsides of any such rules.

The readme states; 

> Also, unlike traditional container builds (e.g. Dockerfile), the Docker images produced by container_image are deterministic / reproducible.

which is misleading of part of the rules include non deterministic behavior. 

I like your workaround to publish the tar of `download_pkgs` and then consume it in later builds, but it definitely deviates from bazel standards and expectations and is definitely harder to setup. If you have any other workarounds or ideas, that would be nice.
