### ISSUE TITLE
Add example for how to use `debs` attribute in `container_layer`

### ISSUE THREAD

**Issue by ilanbiala** [bazelbuild/rules_docker#1523]
The `debs` attribute doesn't fully explain how to get packages installed from apt-get into a Docker image's layer. Can the docs be expanded to clarify this? Also, it seems like there are rules `download_pkgs` and `install_pkgs`. When should those be used compared to `debs`?

**Comment by alex1545** [comment]
Hi @ilanbiala,
The `debs` attribute was deprecated at this point. This was done due to the fact that it only extracted the packages inside the image and didn't actually install the packages themselves (as was expected by the users) because installation required additional steps that need to run a container.
So to install debian packages, we recommend that you use the `download_pkgs` and `install_pkgs` rules. You can read [here](https://github.com/bazelbuild/rules_docker/tree/master/docker/package_managers) more about these rules and find some examples [here](https://github.com/bazelbuild/rules_docker/blob/fa5f719663ca392fdd4bcc68785e7350779c9aa1/tests/docker/package_managers/BUILD).
Feel free to reopen the issue if you have further questions.

**Comment by ilanbiala** [comment]
@alex1545 thanks for the info. Can you add those links to the `debs` doc section for others?

**Comment by ilanbiala** [comment]
Also another 2 things I noticed:
- It's quite hard to really understand what's going on in the test file and how to use `install_pkgs()` as the base for a `container_layer()`. It would be useful to have a simple download, install, layer/image example without all the test wrappers in that file as an example.
- The packages are outdated if `apt-get update` isn't run to get the latest packages. How can I get the latest packages from the default repositories with `download_pkgs()`?

**Comment by dragonsinth** [comment]
+1 the example is very confusing
