### ISSUE TITLE
container wait cmd fails in the `container_run_and_extract()` rule

### ISSUE THREAD

**Issue by mmellin** [bazelbuild/rules_docker#1543]
Within the extract script (`/docker/util/extract.sh.tpl`), there is a `wait` called on a container ID.  I have seen issues where the container which is running the extract completes too fast and has exited prior to this `wait` being called. A returncode of 1 is always returned when `wait` is called on an exited container and the rule breaks.

This is causing transient issues within our CI system.  Sometimes the rule passes, other times it fails.  The lines in question are:

```
id=$($DOCKER $DOCKER_FLAGS run -d %{docker_run_flags} $image_id %{commands})

retcode=$($DOCKER $DOCKER_FLAGS wait $id)
```

A typical error message seen:

```
[2020-06-25T11:37:19.399Z] ++ /usr/bin/docker run -d 58cc723d6e8570c96ea42da42d9b428ae1f4c5908d82574b86acf3be9a218f37 sh -c 'tar -xvf /root/pkgs/helm-diff-linux.tgz -C /tmp && rm -rf /root/pkgs'

[2020-06-25T11:37:19.399Z] + id=102bf0aced403efa0163f175e4e318d970476e58308a99740187bf3af99fcab4

[2020-06-25T11:37:19.399Z] ++ /usr/bin/docker wait 102bf0aced403efa0163f175e4e318d970476e58308a99740187bf3af99fcab4

[2020-06-25T11:37:19.399Z] + retcode=1

[2020-06-25T11:37:19.399Z] + '[' 1 '!=' 0 ']'
```

**Comment by alex1545** [comment]
Hello @mmellin,
It's hard to tell as to why your CI sometimes passes and sometimes fails to run your `container_run_and_extract` targets, but IMO a running container that completes running your commands very fast isn't the issue here. Calling `docker wait` on a container that has existed doesn't return an error and is a valid operation. My guess would be that what you run inside your container sometimes fails. I tried reproducing by running `touch /foo` inside my container and extracting the file multiple times, but it never failed. Maybe if you could find a scenario that you can get failing locally (at least sometimes) that I could try and reproduce, then I may be able to help further.
