### ISSUE TITLE
Bind Mount supported in the container-image rule

### ISSUE THREAD

**Issue by rban1** [bazelbuild/rules_docker#1544]
Hello,
 I am trying to compose a docker image using the container-image rule and am looking to see if there is support of bind mount type(mentioning the source/destination). I only see the option of volumes. 
Looks like it is not supported? Is it because of the fact that these bind mount points make the image unportable? Is the best practice to just run the mount with docker run command once the image is built?

**Comment by alex1545** [comment]
Hello @rban1,
You are correct that there is no support for bind mount in `container_image`. You can bind mount a specific directory/file to a running docker container. There is no such thing as specifying a directory/file to be mounted for an image. Since the `container_image` rule only builds an image, and it's up to the user how to run containers with this image, it does not make sense incorporating bind mount into the image building process.
