### ISSUE TITLE
container_image labels and stamps with dynamic values

### ISSUE THREAD

**Issue by chrislovecnm** [bazelbuild/rules_docker#1590]
Hi all

I am trying to do 

```python
container_image(
    name = "foo",
    labels = {
        "name":"CockroachDB Operator",
        # FIXME - label does not seem to support this
        "version":"{STABLE_DOCKER_TAG}",
     
    },
    base = "@redhat_ubi_minimal//image",
)
```
The `STABLE_DOCKER_TAG` is not rendering as sent in my print workspace script.   This stamp value is being used to set the tag name in our `container_push` definition and is working fine.

Is this supported, or am I missing something?

To reword this.  How do dynamically render values in the `labels` argument map in `container_image`?

**Comment by chrislovecnm** [comment]
Bump

**Comment by gravypod** [comment]
@chrislovecnm does this issue persist if you do something like this:

```
container_image(
    name = "foo",
    repository = "foobar{BIZBAZ}",
    labels = {
        "name":"CockroachDB Operator",
        # FIXME - label does not seem to support this
        "version":"{STABLE_DOCKER_TAG}",
     
    },
    base = "@redhat_ubi_minimal//image",
)
```

My thinking is this is caused by [this check](https://github.com/bazelbuild/rules_docker/blob/7da0de3d094aae5601c45ae0855b64fb2771cd72/container/push.bzl#L68) not including the labels strings.

If that starts to work then this should be an easy fix.
