### ISSUE TITLE
Windows Containers?

### ISSUE THREAD

**Issue by pcj** [bazelbuild/rules_docker#181]
Has anyone tried building a windows container with `rules_docker`?  Any idea what the issues to surmount would be?

**Comment by mattmoor** [comment]
@dslomov FYI

I'd guess the first hurdle is running the rules on Windows period, but next it would probably be plumbing through platform information from Bazel instead of hard-coding things.

During a relatively recent refactor I exposed some of this stuff as kwargs from the underlying library, so it's possibly all `rules_docker`-side changes, but until I've played a few rounds of whack-a-mole, it is anyone's guess how far we are.

**Comment by nlopezgi** [comment]
https://github.com/bazelbuild/rules_docker/commit/e9e2809b7099f92e46f9e8336cda041ab78fcf35
