### ISSUE TITLE
pull images based on architecture

### ISSUE THREAD

**Issue by grunzwei** [bazelbuild/rules_docker#1849]
# 🚀 feature request

container_pull has architecture attribute. 
in CI and some dev machines, the architecture is amd. in new m1 macs, the architecture is arm.
i would like to set architecture to "auto" and have rules docker pull the correct one.

### Relevant Rules

add feature to d container_pull

### Description

want to build the same bazel build using the same images but based no several different architecture, due to dev and ci variety.

### Describe the solution you'd like

bazel should have the current architecture, no reason for the dev to specify it, have container_pull rule always download the right image based on the architecture, if it's available.

### Describe alternatives you've considered

can define a higher level rule multi_platform_pull that generates several image_pull automatically with different architecture somehow only uses the appropriate one... this may be more customizable... but i'm not sure why customization is needed here.
i'm probably missing use cases... but why not always download the images compatible with my architecture? failure to do so will fail the build anyway, as far as i can see

**Comment by gravypod** [comment]
Thanks for dropping this request in here. If we were going to do this I think the approach we'd need to take would be the would be something like `container_pull_multiarch()`. We couldn't have an `arch = "auto"` mainly because of predictability concerns. 

For example on Docker's [official ubuntu image](https://hub.docker.com/layers/ubuntu/library/ubuntu/xenial-20210416/images/sha256-e8eb681cb9e01f339e1d68a47bf6d08a876f875ecf68f263891770bdc3400485?context=explore) you can see for `ubuntu:xenial-20210416` the different architectures have these SHA256s:

1. **linux/arm64/v8**: `e8eb681cb9e01f339e1d68a47bf6d08a876f875ecf68f263891770bdc3400485`
2. **linux/amd64**: `89fd38d069a9a369525ade2bfb6922e62422db58813fccac0ecc1e59dfab0a59`
3. **linux/386**: `4fb5e9fd761ba25ce983c6c87b811fc583ce1a63866b51a32cffb71dd91d6d91`

As you can see for the same image tag there's actually a different SHA for each container. This makes sense because the SHA is (warning: simplification) essentially just `sha256sum {arch}.tar` and every OS & Arch combination has different ABIs/opcodes so they compile to different SHAs. 

This would look something like:

```
workspace(name = "myworkspace")
container_pull_multiarch(
  name = "ubuntu"
  registry = "index.docker.io",
  repository = "ubuntu",
  digests = {
    "@myworkspace//platforms:linux-x86": "sha256:89fd38d069a9a369525ade2bfb6922e62422db58813fccac0ecc1e59dfab0a59",
    "@myworkspace//platforms:linux-arm64v8": "sha256:e8eb681cb9e01f339e1d68a47bf6d08a876f875ecf68f263891770bdc3400485",
    "@myworkspace//platforms:linux-386": "sha256:4fb5e9fd761ba25ce983c6c87b811fc583ce1a63866b51a32cffb71dd91d6d91",
  },
)
```

On top of this someone could write something like Gazelle that you could do:

```
<tool> -target "ubuntu" -os linux -arch x86,armhf -image ubuntu:xenial
```

And it could generate this multiarch target.

**Comment by grunzwei** [comment]
can you advise on how to workaround this issue for now?

**Comment by rmohr** [comment]
> Thanks for dropping this request in here. If we were going to do this I think the approach we'd need to take would be something like `container_pull_multiarch()`. We couldn't have an `arch = "auto"` mainly because of reproducibility concerns.

Was it actually considered to solve this in a fashion like it is done for toolchains? We have for instance in kubevirt an approach based on selects, but it always feels a little bit weird, that the toolchains for the binaries across languages solve this in a unified way but then end up in an incompatible container because rules_docker has no notion of target architecture like toolchains.

**Comment by gravypod** [comment]
@rmohr, I think ultimately a system that was aware of bazel's native primitives (toolchains) would be ideal. I'd love to hear any ideas you have on this topic. Interesting enough the rules for node images sort of work this way. It [copies in a binary from rules_node](https://github.com/bazelbuild/rules_docker/blob/master/nodejs/image.bzl#L139) into the built image. 

**Note**: The following are personal opinions and are not the direction that has been agreed upon by the rules_docker maintainers. This is very likely a bad idea and I just haven't figured out why it's bad yet. 

I'd really love to find a way to take your Bazel toolchain for a language, package them into container, and then package binaries into the containers. Ideally these toolchains could also be entirely self-hosted like Dropbox's self-hosted Python. I've hit issues in the past where I wanted to do something like:

```
# This is just an example that does not work
container_image(
  name = "service",
  binaries = [
    "//service", # Some java_binary I want to serve traffic to
    "//service:healthcheck", # Some py_binary that implements the health check protocol of //service
  ],
)
``` 

It's not currently easy to do this with the existing tools in `rules_docker` since it assumes 1 binary == 1 image when other systems ([k8s](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-liveness-command), [nomad](https://www.nomadproject.io/docs/job-specification/service#check-parameters)) don't necessarily make that assumption.

**Comment by perezd** [comment]
You can workaround this by using select function + @platforms//cpu:*, like this:
```
some_attr = select({
  "@platforms//cpu:arm64": "<some arm image>",
  "@platforms//cpu:x86_64": "<some x86 image".
})
```

This needs to be happening in either a macro or a BUILD file, you can't do this in Starlark rules directly because of when/how they are evaluated.
