### ISSUE TITLE
Finish migrating rule names from container_* to oci_*

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_docker#1885]
Our README says:
> We also have early-stage oci_image, oci_push, etc. aliases for folks that enjoy the consistency of a consistent rule prefix.

We should probably either finish this rename, or remove the oci_* rules

Technically a container is what you get when you `docker run` an OCI image, so the pedantically correct names would be `oci_*` for most of our rules.
But the breaking change of renaming things might just not be worth it. Even in the best case where we provide a buildozer script that updates everyone's BUILD files, you still have to retrain users and lots of user-written documentation becomes out-of-date.

**Comment by dzintars** [comment]
I can speak from "new" user perspective.
You are right about confusion. Bazel is not the simplest tool out there. If we layer on top of that outdated articles, GH repos, etc., it gets even more confusing.
BUT, IMHO this renaming is not the most confusing/complicated thing at all. It just costs come explicit mentioning in documentation front pages.
In the "grand schema" of things, this should be done anyways. This is the right thing, because we definitely are operating with the images and not the containers (which by itself is confusing). And this should be done while community is smaller.
IMHO `rules_docker` also should be renamed to `rules_oci` or `rules_containers`.

**Comment by gravypod** [comment]
@dzintars, I'd just like to add a note for future readers: we also want to try and do some work with @jonjohnsonjr's tooling in `go-containerregistry` to convert the internal representation of an image/layer to be more inline with OCI standards. Right now container metadata and layers are stored in a more docker-y way which isn't necessarily efficient (this is why we don't build image `.tar`s by default, just individual layers).

If someone is looking for opportunities to contribute to `rules_docker` we can point to some areas. @alexeagle is currently working on porting the test infrastructure from node/python over to this repo. Once that happens we'll be able to do some of these internal refactors more safely.

**Comment by alexeagle** [comment]
I'm way in over my head right now with major refactors going on in rules_nodejs and rules_python as well.

Switching this repo to be purely starlark code on top of OCI format, go-containerregistry and crane is a huge project especially if you want to avoid major breaking changes. On top of that, we churned the maintainers so we don't really have the history and mastery of this codebase required for that.
But with docker's new commercial licensing model it feels like the right thing to do.

It might be easier to start greenfield with a new `rules_oci` and try to attain feature parity.
