### ISSUE TITLE
`bazel run` for container_image is very slow

### ISSUE THREAD

**Issue by drigz** [bazelbuild/rules_docker#200]
If I run `bazel run` to load an image on my system, it takes a long time: 80 to 90 seconds.

By adding `set -o verbose` to the script, I realised this time was spent in `list_diffids()`, which takes a long time to iterate over all the ~2000 images on my system. (I'm trying to find out why there are so many!)

```
function list_diffids() {
  for image in $("${DOCKER}" images -aq 2> /dev/null);
  do
    for entry in $("${DOCKER}" inspect -f '{{json .RootFS.Layers}}' "${image}");
    do
      echo -n $entry | python -mjson.tool | grep sha256 | cut -d'"' -f 2 | cut -d':' -f 2
    done
  done
}
```

I can't see where the result of this (`IMAGES`) is used - is it even necessary?

**Comment by mattmoor** [comment]
THANK YOU!  I have been receiving mysterious reports of slowness in the incremental loader for some time and haven't gotten anybody to actually instrument the script to root cause (lots of images has been my suspicion, but where the time was spent was less clear).

I think what makes the most sense (at least short-term) is detecting the large image volume and falling back on a more complete `docker load`.

/cc @damienmg FYI (initially added the incremental load logic)

**Comment by damienmg** [comment]
Yes the initial logic did not had that problem, it was added to support `docker_import` (see https://github.com/bazelbuild/rules_docker/commit/81ad2847d31e4bec9555bd8c3e3e77304f67de40)

**Comment by mattmoor** [comment]
The initial logic was for v1, a lot has changed :P

**Comment by hsyed** [comment]
On the topic of incremental loading. Would it be possible to bail out if nothing has changed ? Kind of like the java workers, if you build a java binary they report back in milliseconds. It takes a 3-5 or so seconds per layer on my machine. This adds up when loading bundles into docker in a CI script. 

Are the hashes being recalculated on each run ?
