### ISSUE TITLE
Consider setting workdir to runfiles/__main__

### ISSUE THREAD

**Issue by drigz** [bazelbuild/rules_docker#204]
Currently, the working directory for the binary when run with `bazel run` is different to when it runs inside the image. For example, if I create a Python script:

```
import os
print os.getcwd()
```

wrap it up in a `py_image` and run with `bazel run :hello.binary`, I get:

`/path/to/execroot/__main__/bazel-out/local-fastbuild/bin/hello.binary.runfiles/__main__`

but if I run with `bazel build :image.tar && docker load ... && docker run ...` I get:

`/app`

I'd expect to get:

`/app/hello.binary.runfiles/__main__`

As a workaround, I'm changing directory at the start of my script when it's not already inside `__main__`, but it would be good if this just worked.

**Comment by mattmoor** [comment]
I've found that in general assumptions about the working directory lead to incompatibilities between `bazel run :something` and `bazel build :something && bazel-bin/something`.

I'm definitely open to changes here.  `lang_image` is currently me trying to approximate `lang_binary` as closely as possible, but I'd love for the owners of the assorted language rules to take on driving compatibility (and improvements to them).

**Comment by drigz** [comment]
Can you recommend how I should find the runfiles? This seems like a basic question but I can't find the right approach. I've considered:

- recursively search for a directory ending in `.runfiles` in the working directory
- find the prefix of sys.argv[0] ending in `.runfiles`
- take the first element of PYTHONPATH

but they all seem a bit hacky.

**Comment by mattmoor** [comment]
> but they all seem a bit hacky

Couldn't agree more :(

[Here's](https://github.com/bazelbuild/rules_k8s/blob/master/k8s/apply.sh.tpl#L18-L22) what I try to do in all bash, which is tantamount to option `#2`.

**Comment by drigz** [comment]
Based on [this comment from Damien](https://github.com/bazelbuild/bazel/issues/1147#issuecomment-212861515), I guess this is the best we can do.

I'm using this code:
```
  # Try to locate the runfiles directory.
  script_path = os.path.abspath(sys.argv[0])
  if ".runfiles" not in script_path:
    raise NotImplementedError("can't find runfiles in " + script_path)
  runfiles = script_path[:script_path.find(".runfiles")] + ".runfiles"
```

**Comment by mickeyzoox** [comment]
@mattmoor Are you sure compatibility with `bazel build :something && bazel-bin/something` is correct? Supporting this requires some odd logic in binaries (for example that drigz posted).

Do you think it would be reasonable to support the `bazel_run.sh :something` (loosely equivalent to `bazel build :something && bazel-bin/something`, except respecting runfiles) instead? See https://github.com/bazelbuild/bazel/blob/master/scripts/bazel-run.sh for the script I'm referring to.

In practice I usually cannot use `bazel build :something && bazel-bin/something` because Bazel doesn't guarantee that this will work. Whereas `bazel_run.sh :something` does the same thing but in a way that is guaranteed to work.
