### ISSUE TITLE
Use java_bin launcher script as java_image entry point.

### ISSUE THREAD

**Issue by hsyed** [bazelbuild/rules_docker#228]
Configuring the JVM at runtime is quite tedious with the current entrypoint.

The standard java_bin has a nice launcher template. Could this be adapted for the `java_image` entry point [see](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/bazel/rules/java/java_stub_template.txt).

**Comment by mattmoor** [comment]
We certainly use the script generated for Python, and we probably should for Java as well to maximize compat.

I think for Java I did this to avoid needing to create a symlink forest putting all of the runfiles into the places the generated script expects them.

**Comment by mattmoor** [comment]
Looking inside one of these scripts, I just realized the real reason we aren't using this: it's a shell script and we don't have a shell :-/

In the Python case, it's a generated Python script.

I'm going to close this for now, but I'm certainly open to suggestions.

**Comment by hsyed** [comment]
A lot of the knobs aren't optional for production use and have to be set before the JVM starts (gc tuning, JMX, RMI, debug etc). Some of these cannot be set after the JVM starts JMX and RMI can though -- but it's somehow not right to configure this in the application.

The most important thing is being able to provide JVM flags in a manageable way in compose and kube manifests. I am currently using the _JAVA_OPTIONS for this but it is hella painful. Being able to supply multiple `jvm-args` switches in the command section or concatenating all the arguments and using them as the jvm args would be good enough.

What options do we have ? What is the overhead of adding the Bourne shell to the java distroless image ? a megabyte or two is justifiable no ?

**Comment by mattmoor** [comment]
Just making sure I understand...

> but it's somehow not right to configure this in the application.

e.g. this rules out `jvm_flags=[]`?

Forgive my possibly naive question, but how does `java_bin` help here?

> I am currently using the _JAVA_OPTIONS for this

I believe this means passing `_JAVA_OPTIONS` as an environment variable is unwieldy?  Probably because it gets so long with lots of options, which can be better decomposed / documented via multiple:
```
  # Pass foo to the JVM because of something.
  "--jvm-args", "foo",
  # Pass bar to the JVM because of something else.
  "--jvm-args", "bar",
  # Who wouldn't pass baz to the JVM?
  "--jvm-args", "baz",
```

>  provide JVM flags in a manageable way in compose and kube manifests

IDK about Compose, but you can expose K8s `ConfigMap` [via environment variables](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#define-a-pod-environment-variable-with-data-from-a-single-configmap).  Have you looked at that (if so, I'm guessing it isn't any cleaner)?
