### ISSUE TITLE
feature-request: Add support to java_images to gather transitive external java deps and tuck them into a intermediate layer implicitly.

### ISSUE THREAD

**Issue by hsyed** [bazelbuild/rules_docker#232]
A spring boot (yes we unfortunately have spring boot in our stack) app has a 60 mb dep footprint, and this is with agressive pruning of deps, a guice grpc-java app has a 20mb intermediate layer.

I knocked this together to gather external deps in all targets and create a Java Provider from them. Using this the top most layer is 750 kb from grpc-java and 4 mb for a huge spring-boot app.

I don't think the multi-external-deps use-case is needed (as if 2 images are in separate repositories they won't be able to use this uber dependencies intermediate layer -- right ? ). so it could be simplified and integrated to just separate the external deps out from java_image implicitly. 

This feature request should probably also make it possible to define this intermediate java_layer without requiring a src's attribute. 

```
def _external_dep_layer(ctx):
  transitive_runtime_jars = []
  exclude = {}
  for provided_dep in ctx.attr.excludes:
    for rt_jar in provided_dep[JavaInfo].transitive_runtime_jars:
      exclude[rt_jar] = True

  for provided_dep in ctx.attr.deps:
    for rt_jar in provided_dep[JavaInfo].transitive_runtime_jars:
      if rt_jar.owner.workspace_root.startswith("external/"):
        if rt_jar not in exclude:
          transitive_runtime_jars.append(rt_jar)

  return [
    DefaultInfo(files=depset(transitive_runtime_jars)),
    java_common.create_provider(transitive_runtime_jars=transitive_runtime_jars)
  ]

java_external_dependencies_library = rule(
  implementation = _external_dep_layer,
  attrs = {
      "deps": attr.label_list(non_empty=True, providers=[JavaInfo]),
      "excludes": attr.label_list(default =[], providers=[JavaInfo]),
  }
)
```

**Comment by mattmoor** [comment]
Have you looked at `layers=[]` instead of `deps=[]`?  If you list the external deps here, they shouldn't be included in the app layers.

The current `layers=[]` is less than ideal (this is definitely a nice heuristic, but it makes the delta when a new external dep is added quite large since all deps are reuploaded).

I'd like to look into "Bazel Aspects" to synthesize a better/dynamic version of `layers=[]`, but haven't found the time.

**Comment by hsyed** [comment]
@mattmoor Sorry for not being clear, I am using layers, and the amazing support for fine layering that works with java (good job on the support !). So, I am using the rule above to to create a Java Provider containing the transitive runtime dependencies of all my microservices and then stick that as an intermediate "layer" of all the microservices  that go into a container_bundle. 

The reason I am going through all this trouble to farm the external deps is that our workspace has 300 external dependencies. I can't manually fine layer them.

Our dependency stack barely changes and if it does a 60mb upload is well worth it. As Bazel is meant for mono repos when it comes to application code all of the business logic is not-external.  
 
* it would be nice for the java_image to support a mode of fine layering where the external deps are extracted from sum of all of the java providers included.
* Layering should be possible without srcs (in an app package it is common to have a local launcher, integration tests and then the docker image, a common pattern is to create a lib and then reuse that in the three targets).
* I include the rule above to give the gist of what I am trying to do -- remove the exludes and it could be used to implement this feature neatly.

**Comment by mattmoor** [comment]
300 layers also wouldn't work as independent layers because of the limitations in most Docker daemon storage drivers (e.g. aufs).

I am currently looking at bringing fine layering to Scala and Groovy based on the shared tools, so I will try to TAL at this once I've wrapped that up (and so we can bring the benefit to all three languages).

thanks for the idea.

**Comment by hsyed** [comment]
Man I suck at 'splainin . the rule above collects all of the dependencies into a single java provider. The java provider generated in the rule above is equavalanet to java library entry that is exporting all the jars discovered to be external.  So the rule above generates a single layer.

Extracted from existing code.

```python
// first create a dummy library listing all the deps that go into the image
java_library(
    name = "modules",
    exports = [
        //.. internal dependencies
       "//cloud/starters/core.common",
      "//cloud/starters/core.persistence",
      ...
    ]
)

// use the rule to create java provider that filters out non external libs
java_external_dependencies_library(
  name = ["external-dep-layer"],
  deps = [":modules"]
)


java_image(
    name = "image",
    // pop the external deps into a layer -- fine layering.
    layers = [":external-dep-layerj"],
   // must compile something or it's an error.
    srcs = glob(["src/main/java/**/*.java"]),
    jvm_flags = [
        "-Xms512m",
        "-Xmx1g",
    ],
    main_class = "...",
    resources = glob(["src/main/resources/**"]),
    resource_strip_prefix = "...",
    // add the deps again as there is no fine-layering support.
    deps = [":modules"]
)
```

**Comment by mattmoor** [comment]
Sorry, that was exactly my understanding. :)

I was just observing that my ambition to leverage Bazel Aspects to reflect the dependency graph into the Docker image's layering (the ideal of BUILD => DEPLOY incrementality) would be hindered in cases like yours due to the storage driver limits and we'd be forced to coalesce layers back together to stay under the limit.

> Layering should be possible without srcs

Regarding this, I believe this should be supported today.  [This](https://github.com/bazelbuild/rules_docker/blob/master/testdata/BUILD#L540-L550) test case should cover it, but there may be bugs.  If so let me know and I'm happy to hunt/squash them.

**Comment by nlopezgi** [comment]
hi @drigz , thanks for your comments. This issue has been open for quite some time and was closed with a proposed solution (the test case pointed to in comment from Nov 15 2017). Could you please explain in more detail your current issue (a repro case or detailed example that enables discussion around the proposal you are putting forward would be good). I'd also advise creating a new issue to discuss the alternative you propose (as I have some doubts the conversation from last year is currently relevant). As for my initial impression of your proposal: in general, having a heuristic to layer deps based on where they come from sounds appealing, but I'm not sure from the top of my head how that would be implemented (i.e., in Skylark), so if you could perhaps expand a bit more on how this might work we can discuss more. It would be even better if you can try sending a PR with a sample initial prototype/test of your approach (e.g., only splitting jars from different repos, or whichever of your list you think is easy-er to implement/prototype). Also, making a change like the one you are suggesting sounds like will require significant effort, (and its not clear to me if this is a big issue or an optimization for a very specific use case) so please explain a bit more what sort of impact we expect to see from this change. Of course, if you are willing to put in the time to work your suggestion through, we'll be happy to help guide you (once we have defined a plan / design to move forward).

**Comment by drigz** [comment]
@nlopezgi, thanks for the quick response! I'm afraid, I can't see any comments/change that resolved the feature-request as I read it (namely, taking advantage of layering without explicitly listing every external dependency of an image). [Matt's comment](https://github.com/bazelbuild/rules_docker/issues/232#issuecomment-344490999) appears to address a different issue mentioned in the original report: "This feature request should probably also make it possible to define this intermediate java_layer without requiring a src's attribute."

@hsyed provided a sample implementation in their initial report, which works very well (although it's obviously harder to use than if it were integrated into `java_image` automatically). For me, it turns a ~30MB layer into a ~29MB base layer of external deps and a 1MB top layer of my code, without requiring a manual separation of dependencies. My comment describes a potential improvement to the proposed approach, but it seems unnecessary to file a feature request for the fine-tuning when the first step still hasn't been taken.

If you think that would be appropriate default behavior for `java_image` (eg when `layers` is not specified) I could look at turning it into a PR.

**Comment by nlopezgi** [comment]
Thanks for the additional info, let me think a bit more about the issue at hand and your proposed solution before having you spend the time to hash this out more. I'll try to get back before eow with more thoughts.

**Comment by nlopezgi** [comment]
is this still an issue? please reopen if so.

**Comment by drigz** [comment]
I can't reopen, but AFAIK this hasn't changed since we discussed it in September.

**Comment by ceason** [comment]
The current `layers` implementation also has the downside of muddying the dependency graph--most of the dependencies I care about putting into layers are 3rdparty libraries which are only transitively (and not directly) related to my `{java,scala,etc}_image` target (where I'm only wiring up the `main` method, parsing arguments, etc). Listing these as `layers` makes them direct dependencies.

I like the idea of using an aspect to separate transitive deps into layers (which would preserve the precision of the dependency graph), but understand the difficulty in finding a universally useful & compatible heuristic. Therefore, I propose using tags on dependencies as a user-configurable mechanism to identify "layer membership" (untagged deps would be aggregated to a single layer) and an aspect to collect a "layer => files" mapping.

For example, the targets:
```python
java_library(
    name = "foo",
    tags = ["container-image-layer=lib"],
    deps = ["@guava"],
)
java_library(
    name = "bar",
    tags = ["container-image-layer=app"],
    deps = [":foo", "@hikaricp"],
)
java_image(
    name = "baz",
    tags = ["container-image-layer=app"],
    deps = [":bar"],
)
```
would yield an image with layers for:
- `:foo`
- `:bar`,`:baz`
- `@guava`,`@hikaricp` (because these are untagged)

Users could manage these tags manually or with a tool like [buildozer](https://github.com/bazelbuild/buildtools/tree/master/buildozer#edit-commands).

Does this seem like a reasonable approach?

**Comment by pcj** [comment]
Closing due to age/inactivity.
