### ISSUE TITLE
Have container_push return more information in the rule struct

### ISSUE THREAD

**Issue by yiyangc91** [bazelbuild/rules_docker#271]
Currently the container_push returns this:

```
struct(
   runfiles = ctx.runfiles(
      files = [
         ctx.executable._pusher,
         image["config"]
      ] + image.get("blobsum", []) + image.get("zipped_layer", []) +
      stamp_inputs + ([image["legacy"]] if image.get("legacy") else []) +
      list(ctx.attr._pusher.default_runfiles.files)
   )
)
```

Would be nice to have the docker image and the docker tag in this, especially due to stamping, so custom rules don't have to reconstruct this information.

```
registry=ctx.expand_make_variables(
        "registry", ctx.attr.registry, {}),
repository=ctx.expand_make_variables(
        "repository", ctx.attr.repository, {}),
tag=ctx.expand_make_variables(
"tag", ctx.attr.tag, {})),

struct(
   runfiles = ctx.runfiles(
      files = [
         ctx.executable._pusher,
         image["config"]
      ] + image.get("blobsum", []) + image.get("zipped_layer", []) +
      stamp_inputs + ([image["legacy"]] if image.get("legacy") else []) +
      list(ctx.attr._pusher.default_runfiles.files),
      registry=registry,
      repository=repository,
      tag=tag,
   )
)
```

**Comment by mattmoor** [comment]
That seems perfectly reasonable to me, can you share some more about what you are trying to do?

One thing to bear in mind is that what your example is publishing won't have stamp variables resolved yet (make variables will be resolved).

Would you be open to turning this into a PR?

**Comment by yiyangc91** [comment]
Hi Matt,

Might be approaching this from the wrong angle actually.

We have a custom rule that depends on the container_push() rule that needs the docker registry, repository, and tag. Something like

```
generate_properties(
    name = "props",
    registry = "docker.example.com",
    repository = "my/image",
    runAfter = "//cmd:container_push_cmd"
)
```

The docker image and tags are hard coded. It probably would be a lot better if the implementation somehow had access to the docker image and tag.

```
generate_properties(
    name = "props",
    pushed_container = "//cmd:container_push_cmd"
)

# Where the impl would contain something like
def _impl(ctx):
   # Do things with theses variables
   # Not actually sure if this is possible... might need to check.
   ctx.attrs.pushed_container.data_registry
   ctx.attrs.pushed_container.data_repository
   ctx.attrs.pushed_container.data_tag

```

I'm not too sure if this is the correct way to go about this.

**Comment by ash2k** [comment]
I.e. we want to push a container and then write information about it into a file. Ideally as a single `bazel run/build` invocation, but two separate ones to do these two things will work fine too.

**Comment by mattmoor** [comment]
@yiyangc91 That looks right, but bear in mind those properties will be populated **even if you do not run the command** (and they will still contain stamp variables).

I think having a **build** output is of limited use because of this, and Bazel will actually freak out about outputs that are only produced by **run** (on `build` is will say the output wasn't produced).

Technically you can pass through arguments to the pusher via:
```shell
   bazel run :push_target -- --args
```

I'd be open to the prospect of adding an optional argument into which we'd write a `json` manifest of what's pushed.  Tools wrapping the `docker_push` target could then supply this argument when they invoke it.  I think that this might address both of your use cases.  Let me know if that makes sense (or not).

**Comment by ash2k** [comment]
@mattmoor That would work perfectly for us, I think.

/cc @kopper

**Comment by kopper** [comment]
@ash2k I think we are approaching this from wrong angle. What we are trying to do is 1. compute image and tag & push 2. compute the same image and tag & use it in deployment templates, i.e. we are trying to compute the same image and tag twice (once with bazel run and once with bazel build, which is an issue, because they must be run separately). More intuitive would be 1. compute image and tag 2. use them for push 3. use them for deployment.

IMO stamping is fine solution (point 1), but what would be even better is go_image outputting image hash plus an option to use it as a tag in container_push (or no tag at all if the hash was the same as the hash Docker registry assigns to the image).

**Comment by mattmoor** [comment]
@kopper the underlying library supports push-by-digest, but I'd be surprised if this was widely supported by registries.  It you look at the way `rules_k8s` uses these rules, it publishes the image and then substitutes the digest into your K8s config, so you always get exactly what you pushed.

`rules_k8s` has its own "resolver" that performs this more complicated push-and-resolve, but using the same underlying library.

**Comment by mattmoor** [comment]
Also, it's not particularly well documented but `bazel run :k8s-object-target` will print out the resolved yaml for the object.

**Comment by kopper** [comment]
Thanks @mattmoor . So `rules_k8s` basically 1. publishes the image 2. gets digest from registry 3. uses the digest in deployment templates all in one bazel executable rule.

If our current approach with stamping becomes painful for whatever reason I'll take a look at applying the same pattern.

**Comment by kopper** [comment]
Given that getting the digest is a separate REST call it could make sense to create separate get_digest rule.

**Comment by jonjohnsonjr** [comment]
There shouldn't be a need to make a separate call to get the digest, since the client already computes the image's digest as part of the manifest PUT. I'm not sure if the implementation currently takes advantage of that.

**Comment by kopper** [comment]
> I'd be open to the prospect of adding an optional argument into which we'd write a json manifest of what's pushed. Tools wrapping the docker_push target could then supply this argument when they invoke it. I think that this might address both of your use cases.

Yes, please. Although everything seems to be already available in standard output we'd definitively prefer a json manifest with stable "schema".

**Comment by kopper** [comment]
@ash2k @yiyangc91 I'm leaning toward writing a Python script that will:
1. call bazel container_push
2. grab digest from it's output (currently stdout but hopefully soon json file)
3. generate k8s template using the image digest instead of tag
4. kctl apply the template

It seems to me that using Bazel for anything more than pushing the image is madness, because Bazel is not Make, it is not for defining "run X after Y" kind of dependencies, esp.:
- bazel run command should never depend on output of another bazel run command (e.g. deploy after push),
- bazel build should never depend on output of bazel run command (e.g. generate template after push).

**Comment by mattmoor** [comment]
So in a slightly different order, this is precisely what `rules_k8s` does.

Instead of generating the template around the digest post-push, you can generate the template around a placeholder tag during BUILD (e.g. [using jsonnet](https://github.com/bazelbuild/rules_k8s/blob/master/examples/hellohttp/java/BUILD#L35) or another templating language).

Then `rules_k8s` marries these to push and apply on bazel run.

In pseudo-BUILD:
```python

lang_image(
  name = "foo",
  ...
)

build_my_k8s_tmpl(
  name = "bar",
  ...
)

k8s_object(
  name = "baz",
  template = ":bar",
  images = {
    "the-image:latest": "foo"
  },
)
```

Then `bazel run :bar.apply` does exactly what you want.

No pressure obviously, I'm just trying to save you from writing and maintaining some code, if I can.

**Comment by kopper** [comment]
@mattmoor We were using `rules_k8s` not so long time ago, but we changed our approach because we needed more sophisticated templating AND we wanted to split pushing the image and deploying k8s objects. Our build and deploy steps are separated and might run on different node. Using `rules_k8s` in deployment step was causing everything to rebuild.

**Comment by kopper** [comment]
There are two viable options for us: either call fast_pusher.py directly or use json output from container_push. We'd prefer the latter.

**Comment by kopper** [comment]
> Perhaps, but it should produce identical bytes in the end. :)

Yeah, but rollbacks are slower :)

**Comment by mattmoor** [comment]
If you've saved the output of `rules_k8s`, that's about as fast as you are gonna get (rollback is exactly what changed).  

Second to that is distributed caching / execution of the build, which is also *kinda* the above...  This is effectively what you're talking about too since you'd be slowing yourself down ensure images still exist on `bazel run` (or post-facto publishing), vs. simply deploying their digests (why the above is still faster).

I'd opt for option 1 (saving configs) because these are small text files, vs. the inputs for fast_pusher, which are large binary inputs.  Either way you're persisting something across machines.

**Comment by jmendiara** [comment]
> I'd be open to the prospect of adding an optional argument into which we'd write a json manifest of what's pushed. Tools wrapping the docker_push target could then supply this argument when they invoke it. I think that this might address both of your use cases. Let me know if that makes sense (or not).

That would be great, as our use case is similar to @kopper, and we want to have our deployment isolated from pushing, and would be great to grab digests to latter usage
