### ISSUE TITLE
Does container_push support reusing already pushed layers?

### ISSUE THREAD

**Issue by wjywbs** [bazelbuild/rules_docker#282]
In docker push, there are "Mounted from other/image" statuses shown for some layers that are the same in another image in the registry. container_push seems to only detect the same layers in itself; i.e. it does not check for layers in the registry, or two container_image rules have the same container_image as the base. This results in slower and larger pushes.

**Comment by mattmoor** [comment]
The answer to this is somewhat nuanced, because there are actually a few "fast paths".  I'll try to explain.

1. The client does always perform `HEAD` existence checks on blobs, so they aren't ever reuploaded to the same repository (for some registries like gcr.io, blobs are shared by the whole project, not just one repository, so this is sufficient).

1. The protocol also supports "mounting" (and the underlying library supports this), but the current client doesn't leverage it.  There are generally two signals that feed the mounting heuristics in the Docker client:
 - From which repo(s) has a given layer been pulled (we could propagate this information from `docker_pull` and leverage it, but don't currently)
 - To which repo(s) has a given layer been pushed (we don't have the global context of the Docker daemon to track this information across pushes).


It feels like the second part of `2.` is what you want.  Tracking this kind of global state in this setting is awkward, but we could potentially have enough context to elide these uploads in your case if we were to rework the way the `container_bundle` form of `container_push` (which lives under `contrib/`) works**.  You can see an example of this kind of multi-push [here](https://github.com/bazelbuild/rules_docker/blob/master/testdata/BUILD#L376-L402).


** - e.g. to go through a single tool that's aware of all concurrent pushes (like the `resolver` in `rules_k8s`), and can tell each to mount from the rest.

**Comment by nlopezgi** [comment]
is this still an issue? please reopen if so.
