### ISSUE TITLE
Fast local working pattern

### ISSUE THREAD

**Issue by mouadino** [bazelbuild/rules_docker#294]
I have been thinking for a while whether I should write an issue or not, mainly concerning whether this is an issue in documentation or not, but anyway, here it is, feels free to close and point me to where we can have this discussion because I am quite intrigued on how others do it.

We are using Bazel for local development combined with docker, which mean Bazel build images then we run them locally, however, the process has been slow due to the shortcomings of this extension IMHO, to be more precise what we do is the following:

- Find what needs to be built (we use `tags` attribute to filter what we want to build) however we cannot use `--build_filter_tags`, instead, a combination of `bazel query ...` (not totally correct but see side notes for more information) and `bazel build ...` with specific parameters.
- Since we need to have images locally we need to suffix targets with `.tar` (that's why we cannot use something like `bazel build --build_filter_tags=tag1,tag2,-tag3 //services/...`.
- After build finish we use `docker load -i` to load images, we run each load in parallel using GNU parallel.

In the ideal case, this is how it should be:

- `bazel query ...` is slow and annoying, preferably we should use `--build_filter_tags` but then how can we tell Bazel to build `.tar` instead of images!?
- `bazel run ...` can only run one target at a time, which means we are stuck using `bazel build ...` and `docker load -i ...` for multiple images else you will need to do it sequentially for each image, which is way slower, how to make process of loading images faster, b/c when you use `docker build ...` it blazingly fast compared to Bazel way, what the recommended way!?

*Sidenote:*

- We don't really use `bazel query ...` b/c this end up to be a problem since this later is very silent when it has to fetch dependencies defined in WORKSPACE, which also means user experience wise it sucks. 

Thank you for your time :)

**Comment by mattmoor** [comment]
> I have been thinking for a while whether I should write an issue or not

When in doubt, open an issue, even if it's just to ask a question.  There are other forums, but this is probably the best since it is dedicated.

> `bazel run ...` can only run one target at a time

I think that what you want is `container_bundle` ([example](https://github.com/bazelbuild/rules_docker/blob/master/testdata/BUILD#L326-L333)), which puts multiple images into a single tarball.  It also has a `bazel run` target, which should incrementally load things.

Note that you don't need to suffix `.tar` on anything but the leaves.  Here you'd only do it when building the `container_bundle` target.  There's some nuance here, that I'd be happy to help you walk through.  tl;dr specifying `.tar` should always work, but may be (dramatically) slower.

**Comment by mouadino** [comment]
@mattmoor Hey Matt, thanks for the quick reply, regarding `container_bundler` I am aware of it but doesn't solve the issue in hand as far as I understand it, because what we are looking for is a way to *dynamically* find images to build and (optionally) load them locally, the dynamic part is important which is what `container_bundle` doesn't provide, this is why we use `tags` to find what we want to build, an example will be a user want to build all code related to X (which happen to be a tag and targets with this tag are scattered through our mono-repository) in this case X can be anything from "programming language", "team name", "service name", "architecture layer" ..., and when I say optionally load them locally I think here it's necessary to build a `.tar` and use `docker load -i ...` specially if we are going build multiple targets/images which is what we do most of the case, the way it's done right now is ugly also but in (pseudo/bash)-code, it's like this:

```
# Here we formulate a query that check tags for a given TAGS environment variables.
pkgs=$(bazel query --output=package ...)
args=""
for pkg in $pkgs; do
   # The compose target is target responsible of build docker-compose.yml. 
   args="$args $pkg:image.tar $pkg:compose"
done

bazel build -- $args

# Here we use GNU parallel when available, but for simplicity, I removed this part, but in anyway this is a very slow operation.
for pkg in $pkgs; do
  docker load -i bazel-genfiles/$pkg/image.tar
done
```

Else ideally, what I would love to have is:

```
bazel build --build_tag_filters=$TAGS //services/...
```

Which will build all targets with passed TAGS (which we do take care of) and load them in docker, taking advantages of Bazel parallel execution and build only what changed.

**Comment by mouadino** [comment]
> So this almost meets your needs, but IIUC doesn't because it selects the main build target, not the implicit .tar target?

Exactly, however, to use `docker load -i` you need the tarball, which means you need to build `<name>.tar` target and not default which only produces scattered layers.  

> So if you were to build N of these scripts using your original command (w/ --build_filter_tags), and then use GNU parallel to run them all in parallel, it might be what you are looking for (and should be significantly faster).

Right, this definetly is an improvement, but still, you will need to know what changed which mean you will need to do a `bazel query ...` and sometimes run a command even though nothing changed, an example of what the bash code will look like:

```
bazel build --build_filter_tags=$TAGS //...

# Here we need to find what just have been built, however, I don't know if it's possible to do so, so we use "Bazel query" to return all packages, although it can return packages where nothing have changed.
parallel bazel-bin/{}/image --norun ::: $(bazel query --output=package ...)
```

So my other question will be can we know what built after a `bazel build` happen to not end up running useless things? especially given that loading image is not that cheap.

**Comment by mattmoor** [comment]
### re: dynamic target selection and execution

I'm not aware of a good way to do this with Bazel (doesn't seem directly related to these rules).

@davidstanke should probably better understand your use case.

### re: running useless things

Squinting and looking at this problem, I can see similarities to the problem of publishing N images to a registry as quickly as possible, which is one I've studied *a lot*.

You're (now) running N scripts to incrementally publish N images to the daemon (vs. registry).  The incremental load script (like publishing to a registry) performs existence checks to elide layer loads.  When it misses, it uploads.

Generally the route I've taken in the registry case is to make "do nothing" as fast as conceivably possible.  Then for cases of incremental change, run everything (and the "do nothing" cases should be hidden in the slack of the rest).

I think the best answer is that we need a more efficient (and [portable](https://github.com/bazelbuild/rules_docker/issues/72)) incremental load script, that likely speaks to the daemon directly.  That said, I'm not sure the daemon can be as fast in the "do nothing" case because it is (may be) less optimized for shedding existence checks quickly.

This is also relevant to [this](https://github.com/bazelbuild/rules_k8s/issues/9).  /cc @dlorenc @r2d4

**Comment by mouadino** [comment]
Just small update, today I tried to use `--build_event_json_file` to save build events and parse them to see what was build and was not but without success, but sadly the events produced in both cases (where there is something to build "noop build" and something to build "dirty build") are undistinguished, at least not in structured way (the logged messages are different), which is confusing b/c I will have expected the "dirty build" to contain an event like [TargetComplete](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/buildeventstream/proto/build_event_stream.proto#L454) with the image target and the "noop build" to not contain it, but the `TargetComplete` event is nowhere to be found in both :(

**Comment by nlopezgi** [comment]
Hi @mouadino ,
is this issue still relevant? Closing, but let me know if so to reopen

**Comment by gravypod** [comment]
@mouadino I had a very similar need to your use case. I have some containers that I build with bazel and other containers that I pull from public image repositories (PG, Redis, Mongo, load balancers, etc). To do this in an acceptably simple, and easy to understand way, I built a tool that behaves sort of like `docker-compose` for bazel containers. It wraps bazel-watcher, bazel, and docker-compose to watch, build, and restart containers produced in bazel. 

You can find it [here](https://github.com/CaperAi/bazel_compose) if you are interested.
