### ISSUE TITLE
args passed twice to scala_image

### ISSUE THREAD

**Issue by gkossakowski** [bazelbuild/rules_docker#374]
```
scala_image(
    ...
    args = ["foo_bar", "boo"]
)
```

results in:

```
Running command line: bazel-bin/... foo_bar boo
```

being printed but the application actually receives the args twice. when printed from the main method, i get:

```
List(foo_bar, boo, foo_bar, boo)
```

i believe the problem is that `args` are both appended to the luncher script in `jar_app_layer` and passed on to `scala_binary` rule.

**Comment by pcj** [comment]
Thanks @gkossakowski will investigate

**Comment by Globegitter** [comment]
That seems to be affecting not just the scala_image but also py_image and possibly all other images. I think the reason for this is that `args` is a special attribute for bazel and it then passes everything specified there on `bazel run` as documented here: https://docs.bazel.build/versions/master/be/common-definitions.html#common-attributes-binaries

Ideally there was just a way to turn this behaviour off, otherwise we would either have to try and strip the duplicated args manually or rename `args` to something like `entrypoint_args`.

**Comment by Globegitter** [comment]
@mjduijn Yep it probably makes most sense to pass it down as `docker_args` or something similar toget around the bazel behaviour.

**Comment by nlopezgi** [comment]
hi @Globegitter and @mjduijn,
Thanks for creating the issue in Bazel repo and following through with the response. Renaming args to docker_args is not ideal as it diverges the API between xx_binary and xx_image rules. I think our current options are to get this to work properly either for the "docker run ..." use case or for the "bazel run ..." use case, which is also less than ideal. One other possible alternative would be to try to modify the incremental load template to not pass the arguments again. I.e., this line:
https://github.com/bazelbuild/rules_docker/blob/master/container/incremental_load.sh.tpl#L240
is coming out as:
docker run -i --rm --network=host bazel/testdata:java_image "$@"
in the resulting runner
if it was stripped of the "$@" then args would not be passed twice.
My only concern is I'm not sure how this will impact other container_image rules that might be using args.

**Comment by mjduijn** [comment]
There is one other way that I see: renaming the `args` attribute in `jar_app_layer` to something other than `args`.
Your way seems far more elegant, I'll create a PR with the checks in place.
