### ISSUE TITLE
go-containerregistry?

### ISSUE THREAD

**Issue by pcj** [bazelbuild/rules_docker#382]
Now that https://github.com/google/go-containerregistry is out, are there plans to migrate to using that instead of the python impl in https://github.com/google/containerregistry?

Just curious, I don't have any complaints with the python implementation.

**Comment by mattmoor** [comment]
tl;dr I don't think we can do this without a breaking change to how clients consume `rules_docker`.

Because of the `repositories()` pattern for importing skylark rules, `rules_docker` cannot depend on `rules_go` without adding the need to load/call multiple skylark functions...

The only other alternative would be to ship binaries of all the dependent tooling, for every host platform, which doesn't get me particularly excited.

I also think it will be a while before that library has the level of compatibility and maturity of these rules.
