### ISSUE TITLE
Compose from lang_images and container_images

### ISSUE THREAD

**Issue by treuherz** [bazelbuild/rules_docker#423]
Currently, AFAICT, `lang_image` rules have capabilities corresponding to their respective `_binary` rules, where `container_layer` has attributes that are generally useful for creating containers (e.g. `symlinks`, `empty_dirs`, `user`), but there doesn't seem to be a good way to combine these. You can't do this:

```
java_image(
   name = "java-layer",
   ...
)

container_layer(
    name = "utility-layer",
    ...
)

container_image(
    name = "image",
    layers = [
        ":java-layer",
        ":utility-layer",
    ]
)
```
because `java_image` doesn't provide LayerInfo. Which kinda makes sense, since it's an "image" not a "layer" (see #335, sorta).

What I don't understand is that you can't do this:
```
container_layer(
    name = "utility-layer",
    ...
)

java_image(
   name = "java-layer",
   layers = [":utility-layer"],
   ...
)
```
because `java_image`'s layers have to provide CcLinkingInfo or JavaInfo. Unless I were to import a Java base image and do manually in a `container_image` everything `java_image` is doing for me, and have my utility layer be a layer of that new image, there doesn't seem to be a way to combine the functionalities of the two types of image rule.

I think teaching the `lang_image` rules to accept the LayerInfo provider seems like the most straightforward way of making this work, but I'm sure there are downsides there that I can't see.

**Comment by nlopezgi** [comment]
container_layers is a recent feature and has only been implemented support for in comtainer_image. I do think it should be possible to have lang_image rules accept the layers as well. If you want to send a PR to try doing this we'll be happy to review

**Comment by mjduijn** [comment]
I would like to pick this up, but for the proposed approach I am stuck.

The problem is that the `layers` argument to `lang_image` is also passed as part of `deps` to `native.lang_binary` along with the specified `deps`.
What I can't figure out is how to distinguish container_layers from valid lang dependencies when provided in the `layers` argument.

I'm very new to Bazel and a hint would be very much appreciated.

**Comment by nlopezgi** [comment]
Thanks for trying to pick this up. wrt to your specific question of how to accept layers in the lang_image rule so that its not passed as deps, I would have to look at the code to figure out why it is also ending up in the deps (which should be avoidable, I think). In any case, I have been thinking more about this request; the main issue we would have to accept this change is that lang_image rules are kept in sync with lang_binary rules; adding the layers attribute would break this sync (we will be discussing in the future if we want to maintain this sync, as we are aware of the trade-offs that this is bringing).
