### ISSUE TITLE
'repository name must be lowercase' error when compiling a `java_image` step - Any way to fix without renaming directory?

### ISSUE THREAD

**Issue by Jdban** [bazelbuild/rules_docker#453]
```
$ bazel run //java/projects/FileParser:FileParserDocker
...
Error parsing reference: "bazel/java/projects/FileParser:FileParserDocker" is not a valid repository/tag: invalid reference format: repository name must be lowercase
```

Is there any way to fix this without changing the directory name? I'm willing to add an extra flag for this.

**Comment by nlopezgi** [comment]
The restriction to use lowercases is imposed by docker directly, not by the rules. Currently there is no way to override the use of "package_name:target" in the container rules. The one way I can think of implementing this without making it specifically about lowercasing the package_name, is to allow overriding it. However, I'm hesitant to allow overriding the use of "package_name:target" as other rules might be dependent on this (thus making the use of the override incompatible with those other rules) and it opens the doors for users to shoot themselves on the foot (if you happen to name two images with the same name the behavior of the rules wrt re-building, re-pushing images might be unexpected). Also, java practices (afaik) typically recommend directories be all lower case, so I don't think providing the override due to having directories with upper case is a common enough use case to warrant dealing with the issues it might cause. 
Do you have other ideas as to how to deal with your use case in the rules (i.e., what would the flag you envision do)?

**Comment by Jdban** [comment]
Gotcha, I follow. Yeah, I'm not sure how to allow it then. I just don't like the restriction on folder naming, but I guess it's reasonable.

**Comment by roblg** [comment]
FWIW, I also ran into this with just a "bare" `container_image` call, so it's not specific to the `java_image` rule. Is there no other way around this? It seems sort of arbitrary/restrictive that we have to lowercase all folder names in a package path where we want to build a container image, or build containers outside the package that contains their sources. I can definitely see the potential pitfalls with container name collisions, but that seems like a thing that would happen even if images were being managed outside of rules_docker I think? 

For now I guess we can go with a parallel set of packages specifically for the containers for our apps, but at first blush it seems like it would be nice if we could keep things together.

**Comment by nlopezgi** [comment]
@roblg thanks for commenting.
The restriction on lowercase names comes from upstream restrictions in docker container names, its not something we can directly change in these rules. Given this restriction exists, the question is which kind of workaround would be feasible and does not create more problems than it solves? I cannot think of a way to enable package names that have uppercase letters which would not create more problems or edge cases that would be really painful to deal with. I'm open to any concrete suggestions if you have any!
