### ISSUE TITLE
container_pull and container image using a specific base images creates non-loadable tar file

### ISSUE THREAD

**Issue by guytt** [bazelbuild/rules_docker#474]
Hi,

To recreate - 

1. Define the following rules:
```
container_pull(
    name = "bazel-testers_1.0.0",
    registry = "index.docker.io",
    repository = "guyt2004/bazel-testers",
    tag = "1.0.0"
)

container_image(
    name = "bazel-testers_1.0.0",
    base = "@bazel-testers_1.0.0//image",
)
```
2. Run a bazel action that triggers the creation of a tar file that should contain the image defined above. 
3. Run ```docker load -i <path to output tar file>```

The error I get is:
`invalid manifest, layers length mismatch: expected '\x11', got '\x0e'`

Dockerfile content of the source image:
```
FROM ficusio/node-alpine:5.7-onbuild

EXPOSE 3000
EXPOSE 3001

CMD ["node", "index.js"]
```

Tried to use the base image without my own layer (i.e. referencing ficusio/node-alpine:5.7-onbuild in my docker rules). This has rendered a **loadable** tar.

Thanks for helping!

**Comment by guytt** [comment]
FYI - happened again, this time with a generally available image:
**mesosphere/mesos-master:1.0.0**

```
container_pull(
    name = "mesosphere_mesos-master_1.0.0",
    registry = "index.docker.io",
    repository = "mesosphere/mesos-master",
    tag = "1.0.0"
)

container_image(
    name = "mesosphere_mesos-master_1.0.0",
    base = "@mesosphere_mesos-master_1.0.0//image",
)
```

Error is:
`invalid manifest, layers length mismatch: expected 12, got 11`

**Comment by mattmoor** [comment]
/assign @nlopezgi 

The problem is that the list of `diff_ids` in the "Config" and the list of layers in the "Manifest" must match.  We elide layers from both when they are empty, but only seem to be eliding one of them in this case.

**Comment by nlopezgi** [comment]
Thanks, will look into it this week.

**Comment by xingao267** [comment]
I'm looking into this. It seems rules_docker doesn't handle empty layer correctly.

**Comment by xingao267** [comment]
After looking into this, I think the reason why this is happening is because these images (bazel-testers_1.0.0 and mesosphere_mesos-master_1.0.0) contain a mix of legacy and new empty layers. Before Docker 1.10, empty layers are recorded in the image's manifest.json file, and the corresponding layer folder with layer.tar is created, which would be empty. After that, empty layers are not put into image configuration any more (ref: https://github.com/moby/moby/issues/22072). containerregistry works fine when the image only contains legacy empty layer or new empty layer, but not both. I'm working on a fix in that repo. It's kinda hard to create a very slim testing image for this (with both legacy and new empty layer). I had to use rules_docker to mimic the behavior that legacy version of docker would give.

**Comment by ittaiz** [comment]
Thanks!
How long does this usually take? (Hours, days, more)?
Also,
rules_docker will need to update its version of containerregistry, right?
Will you be able to help with it?

**Comment by xingao267** [comment]
@ittaiz They said they will try to get to it today. I'll ping them as well.

Yes. After that change is in GitHub, I'll update rules_docker.

**Comment by xingao267** [comment]
Hi @guytt I've sent the PR to update the containerregistry pin. It seems there is something broken in travis-ci. I've upstreamed the issue there.
