### ISSUE TITLE
Docker image tarballs have wrong created time when imported to Docker

### ISSUE THREAD

**Issue by jimmidyson** [bazelbuild/rules_docker#52]
```bash
$ docker images|grep dummy

dummy/web                                                  latest                    df93a33aa16b        292 years ago       21.1MB
```

I also noticed that all files in the tarball have a created date of `1970-01-01 01:00`:

```bash
$ tar tvf bazel-bin/docker.tar

-rw-r--r-- 0/0             606 1970-01-01 01:00 df93a33aa16b04e027f600b2f429e80a8b6a8896d035910ec5b90109269d3326.json
-rw-r--r-- 0/0               3 1970-01-01 01:00 9f8383f973c5c7dece737d92e6587a0f37002b20287303512f260d6a506bf4f4/VERSION
-rw-r--r-- 0/0         9482240 1970-01-01 01:00 9f8383f973c5c7dece737d92e6587a0f37002b20287303512f260d6a506bf4f4/layer.tar
-rw-r--r-- 0/0             349 1970-01-01 01:00 9f8383f973c5c7dece737d92e6587a0f37002b20287303512f260d6a506bf4f4/json
-rw-r--r-- 0/0               3 1970-01-01 01:00 fb8b0e2a7f9d34c6bd92e1700b942fe81e3603d021fc442470cdd8227d3dbc7a/VERSION
-rw-r--r-- 0/0        11950080 1970-01-01 01:00 fb8b0e2a7f9d34c6bd92e1700b942fe81e3603d021fc442470cdd8227d3dbc7a/layer.tar
-rw-r--r-- 0/0             241 1970-01-01 01:00 fb8b0e2a7f9d34c6bd92e1700b942fe81e3603d021fc442470cdd8227d3dbc7a/json
-rw-r--r-- 0/0               3 1970-01-01 01:00 07dd64f81c937fe7a80aabfb2b5376e80746bed42e8a89c74bf2c579b553dd50/VERSION
-rw-r--r-- 0/0           10240 1970-01-01 01:00 07dd64f81c937fe7a80aabfb2b5376e80746bed42e8a89c74bf2c579b553dd50/layer.tar
-rw-r--r-- 0/0             178 1970-01-01 01:00 07dd64f81c937fe7a80aabfb2b5376e80746bed42e8a89c74bf2c579b553dd50/json
-rw-r--r-- 0/0              95 1970-01-01 01:00 repositories
-rw-r--r-- 0/0             367 1970-01-01 01:00 manifest.json
```

**Comment by mattmoor** [comment]
This is all by design (which sounds horrible), let me explain.

The former is because we *omit* timestamps in the config files, and Docker picks some random time (not the Unix epoch) out of thin air.

Both are in pursuit of reproducible builds.  I believe you'd also see the latter if you looked inside of a JAR file Bazel produces.

Ultimately the decision comes down to a trade-off between something largely cosmetic (timestamp) and something that fundamentally improves numerous things, including:
1. Repeatable builds are the holy grail of provenance
1. Same input => same layer means better distributed caching
1. Same input => same layer means better push / pull incrementality

I could go on, but these are some of the highlights.

I think our best case would be for Docker to do something more sensible when this is omitted.

**Comment by mattmoor** [comment]
With stamping, we could allow timestamps to creep in, but Skylark doesn't yet support this well.  What we have with `stamp = true` is essentially a workaround.

**Comment by jimmidyson** [comment]
Your explanation re reproducible builds makes total sense - thank you again.

**Comment by Globegitter** [comment]
@mattmoor I now have an issue where I want to create a docker image with bazel installed. I now get it to install as discussed here: https://github.com/bazelbuild/bazel/issues/4492

But now the problem is bazel itself checks the creation dates of those files and errors out with: `Error: corrupt installation: file '/opt/bazel/_embedded_binaries/A-server.jar' modified.  Please remove '/opt/bazel' and try again.` I can of course run `touch -m -t 202801010101 $(find /opt/bazel -type f)` as a first command but that takes 6-7s, making it again less suitable for CI.

Seems like this issue could also be fixed with the stamping feature, by allowing a separate timestamp for tar extraction.

**Comment by rbtcollins** [comment]
So, Docker are punting on this because OCI mandates it; and pointing at https://github.com/opencontainers/image-spec/issues as the place to push this forward.
