### ISSUE TITLE
Container tars/files are not present in image 

### ISSUE THREAD

**Issue by jacobfederer** [bazelbuild/rules_docker#572]
Hello,

I'm trying to add several sql files to my Golang container. I specified the files in my directory like this:
```
package(default_visibility = ["//visibility:public"])


filegroup(
    name = "sql",
    srcs = glob(["*.sql",]),
)
```
and my container image looks something like this:

```
pkg_tar(
    name = "sql-files",
    package_dir = "etc",
    srcs = ["//backend/sql:sql"],
    mode = "0o644",
)

go_image(
    name = "docker",
    binary = "//backend:backend",
    visibility = ["//visibility:public"],
    tars = [":passwd_tar","//backend:sql-files"],
    files = ["//backend/sql"],
    user = "nonroot",
)
```

The problem is that the files/tars are ignored and not packaged into the container. I tried several folders like etc, /sql/, /sql and ./sql/, but the files are never present. By inspecting the image like this: 

```
MacBook-Pro-3:tbnext jacob$ bazel run -c dbg //backend:docker
INFO: Build options have changed, discarding analysis cache.
INFO: Analysed target //backend:docker (0 packages loaded, 6970 targets configured).
INFO: Found 1 target...
Target //backend:docker up-to-date:
  bazel-bin/backend/docker-layer.tar
INFO: Elapsed time: 1,231s, Critical Path: 0,03s, Remote (0,00% of the time): [queue: 0,00%, setup: 0,00%, process: 0,00%]
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
Loaded image ID: sha256:323af5cba6fab44df991fbba5af5a5ea546dcafaa4f2257de77f98c194fa3e17
Tagging 323af5cba6fab44df991fbba5af5a5ea546dcafaa4f2257de77f98c194fa3e17 as bazel/backend:docker
standard_init_linux.go:190: exec user process caused "exec format error"
```
(which did not work by the way, so )
`docker run -ti --rm --entrypoint=sh bazel/backend:docker`

there were no files under any of the folders. I even tried to add them as simple files, but still nothing was in the container. The build always ran successfully.

Any help is appreciated.

**Comment by nlopezgi** [comment]
Hi @jacobfederer , thanks for opening this issue
The issue you are having is likely related to problems with running `go_images` from a mac. If you have access to a linux vm please try your setup there. 

Unfortunately running the `xx_image` rules from a mac is not currently supported due to limitations with how most `xx_binary` rules access the host/target tools/toolchain via platforms in Bazel. To verify, you can try doing the same thing with `container_image` instead of `go_image`; if that works but `go_image` does not then the problem is with `go_binary` not supporting the type of cross platform build required for `xx_image` rules to work. It's possible recent changes in `rules_go` (https://github.com/bazelbuild/rules_go/issues/1760) can be leveraged to make this work, but this is something we have not pursued (e.g., tested) ourselves.

**Comment by jacobfederer** [comment]
I ran all of my builds also on Google Cloud Build. That didn't change the fact that the tars are missing. I only the debugging commands to find out what's wrong. They are not the real problem.

**Comment by nlopezgi** [comment]
doing this in GCB should be fully supported, can you provide some error traces from that environment (and more details about your GCB build - e.g., which builder are you using) as the error you are included here does not correspond to anything you would ever get on GCB and does not help you at all debug the issues.

**Comment by nlopezgi** [comment]
- you could also try not using the srcs = glob(["*.sql",]), and just list out all the files, Bazel is sometimes funky with these.
- You can also verify the output of the pkg_tar rule, it should contain the files you expect it to have, if not then the error is there and not in the go_image rule
- you can also try (as I already suggested) to use container_image rule instead of go_image rule and see if that helps you

**Comment by jacobfederer** [comment]
Yes, it actually was a problem with the go_image rule. The rule doesn't respect tars as well as files. They will just not be on the file tree without any error message, even if the file doesn't exist.  

Also I noticed that even if I compiled like this:
```
go_binary(
    name = "backend",
    embed = [":go_default_library"],
    visibility = ["//visibility:public"],
    goarch = "amd64",
    goos = "linux",
    pure = "on",
)
```

Distroless couldn't execute the file with the message or something similar: 
`./backend: line 1: syntax error: unexpected word (expecting ")")`

For now I switched to Alpine with the following setup:

```
go_binary(
    name = "backend",
    embed = [":go_default_library"],
    visibility = ["//visibility:public"],
    goarch = "amd64",
    goos = "linux",
    pure = "on",
)

...
pkg_tar(
    name = "sql-files",
    package_dir = "sql",
    srcs = ["//backend/sql:sql"],
    mode = "0o644",
)

container_image(
    name = "docker",
    base ="@alpine_base//image",
    visibility = ["//visibility:public"],
    tars = [":passwd_tar","//backend:sql-files"],
    files = ["//backend:backend"],
    cmd = ["backend"],
    user = "nonroot",
)
```

Thanks for your help.
