### ISSUE TITLE
container_layer/image debs not being applied.

### ISSUE THREAD

**Issue by Chronojam** [bazelbuild/rules_docker#611]
Hello,

Given a BUILD file containing the following:

```
container_image(
    name = "container",
    base = "@nodejs_base_image//image",
    layers = [
        "//node:node_modules_layer",
        "//node/packages/health:layer",
        ":layer",
    ],
    debs = [
        packages["fontconfig"],
        # Other debs here.
    ],
    entrypoint = [
        "node",
        "/usr/src/app/index.js",
    ],
    #user = "10000",
)
```

I am not seeing the listed debs applied with either (from inside the constructed container)
``` 
apt list --installed | grep fontconfig 
```
or 
```
ls -lrt /etc/fonts
```
 
I have also tried with vendored .deb files directly:
```
## container/BUILD
debs = [
    "//third-party/debian-packages/fontconfig:debian_package",
]

## third-party/debian-packages/fontconfig/BUILD
package(default_visibility = ["//visibility:public"])

filegroup(
        name = "debian_package",
        srcs = ["fontconfig_2.11.0-6.7+b1_amd64.deb"],
)
```

Environment:
Bazel: 0.18.0
Docker_Rules: v0.5.1
GoogleContainerTools/Distroless: 3585653b2b0d33c3fb369b907ef68df8344fd2ad

Thanks!

**Comment by smukherj1** [comment]
Hi @Chronojam,

Thanks for reporting this issue. The "debs" attribute in "container_image" doesn't actually install the package. It simply extracts the contents of the debian package. Installation involves more steps. We will update the documentation of the debs attribute of container_image. I think the initial hope was extraction of the deb would be equivalent to installing but that is not the case.

In order to install packages in a container, you actually need to run apt-get install or apt install. Consider using download_pkgs from here https://github.com/GoogleContainerTools/base-images-docker/blob/master/package_managers/download_pkgs.bzl#L148 to download debian packages and install_pkgs from here https://github.com/GoogleContainerTools/base-images-docker/blob/master/package_managers/install_pkgs.bzl#L184 to install them. Note that these rules actually launch a docker container and run apt-get to install the packages.
