### ISSUE TITLE
Allow storing file timestamps

### ISSUE THREAD

**Issue by wjywbs** [bazelbuild/rules_docker#633]
I'm not sure if this was requested before, but all files copied in the image in the container_image rule have unix time 0. While this does not affect binary files and makes the image reproducible, some static assets like html, js and image files are expected to have timestamps. Then web servers serving static files in the container can set Last-Modified header, and browsers can cache the files and issue If-Modified-Since requests.

An option to keep the file timestamps will be helpful.

Go's http server does not set Last-Modified header if the modified time is 0:
https://github.com/golang/go/blob/master/src/net/http/fs.go#L484

**Comment by nlopezgi** [comment]
https://github.com/bazelbuild/rules_docker/blob/master/README.md#stamping

**Comment by nlopezgi** [comment]
thanks for the clarifications @wjywbs 
We dont currently support setting timestamps for the individual files. How would you see such a feature working (i.e., would it set the BUILD_TIMESTAMP on all the files, or something else?). I have not had anyone else ask for this feature before. I'd be happy to work with you so you can design it in detail and implement it.

**Comment by tmc** [comment]
https://github.com/bazelbuild/bazel/issues/1299

**Comment by aiuto** [comment]
More background: https://github.com/bazelbuild/bazel/pull/7276

**Comment by tmc** [comment]
With the pkg_tar option added this should be easy to implement now.

**Comment by nlopezgi** [comment]
Great, Thanks! I'd be happy to review a PR adding this feature (+ some tests) if anyone wants to volunteer!

**Comment by wjywbs** [comment]
My understanding of bazelbuild/bazel#7276 is that pkg_tar will set the modified time of all files in this tar to 2000-01-01 00:00:00.000 UTC. In this case, Go's http server [will](https://github.com/golang/go/blob/master/src/net/http/fs.go#L139) set a Last-Modified header. However, when a new image is built with new static files, they have the same modified time. I think when the browser issues If-Modified-Since requests, the browser will not fetch the new static files because the server will return "304 Not Modified".

I also understand ETag is a better solution, but it won't work out of the box without extra code. If I go with the ETag route, I will keep mtime to 0 to avoid the above issue.

If pkg_tar's mtime can be set to the current build time, or more directly, if each file in the tar has the same modified time as the source files, this issue will be solved.

**Comment by fierry** [comment]
What is the ETA for finalizing this feature?

Not having timestamps for files **completely breaks nginx cache** (and any web-server cache). All my files are shown as "Last-Modified: Thu, 01 Jan 1970 00:00:00 GMT". I need to manually trick your build rules by using container_run_and_commit to touch specific files in order to provide timestamp for them - which is a really bad hack...

**By the way**: container_run_and_commit incorrectly breaks cmd parameters. If I specify cmd = ["nginx", "-g", "deamon off;"] the rull will split it into ["nginx", "-g", "deamon", "off;"] which obviously breaks the whole container... I found no way of escaping this splitting...
