### ISSUE TITLE
Run java_image file

### ISSUE THREAD

**Issue by adibrastegarnia** [bazelbuild/rules_docker#640]
Hello, 

I have a couple of questions but I didn't find the answers in README. 

1- What is the difference between java_image and container_image?

2- How can I run them using docker? Is there any example that I can use to run a sample java app that is built using bazel in a docker container?

**Comment by xingao267** [comment]
Hi @adibrastegarnia 

1- What is the difference between java_image and container_image?
container_image builds a general docker image similar to what you would do with "docker build" with a Dockerfile. But instead of specify what to put in the image and other metadata in the Dockerfile, you specify them in a container_image target in the BUILD file, such as the targets in https://github.com/bazelbuild/rules_docker/blob/master/testdata/BUILD.

java_image ([examples](https://github.com/bazelbuild/rules_docker/blob/master/tests/docker/java/BUILD)) is one kind of lang_image. The idea behind these rules is to make containerizing an application built via a `lang_binary` rule as simple as changing it to `lang_image`. In case of `java_image`, you can simply containerize your java binary by replace the target type `java_binary` by `java_image`, and it will create a docker image that containers your java_binary and runtime environment. Some more references are here https://github.com/bazelbuild/rules_docker#overview-1. lang_images are special types of container_image which do more specific things.

2- How can I run them using docker? Is there any example that I can use to run a sample java app that is built using bazel in a docker container?
To run container_image using docker:
1. `bazel run <your_container_image_target>` which will show an image id in the console
2. docker run -it <the_image_id>

To run java_image using docker, I think it's simpler, you just do
`bazel run <your_java_image_target> <args for your java binary>`

Example: https://github.com/bazelbuild/rules_docker/blob/master/tests/docker/java/BUILD#L31
and you can run that execute the following command from the root of your cloned rules_docker repo:
`bazel run bazel run //tests/docker/java:java_image`

**Comment by adibrastegarnia** [comment]
Thanks for your comprehensive response. I will try and let you know if I have more questions.

**Comment by adibrastegarnia** [comment]
I am getting another error that I am not sure it is because of bazel or docker: 

INFO: 320 processes: 320 linux-sandbox.
INFO: Build completed successfully, 329 total actions
INFO: Build completed successfully, 329 total actions
668afdbd4462: Loading layer  18.39MB/18.39MB
6189abe095d5: Loading layer  1.966MB/1.966MB
56f99c131b79: Loading layer    100MB/100MB
1f83d65ad81a: Loading layer  53.98MB/53.98MB
Loaded image ID: sha256:e443f6394ea22014cc06c0c35d3344a26187ad22e72926f0b5a918dff905bf0a
Tagging e443f6394ea22014cc06c0c35d3344a26187ad22e72926f0b5a918dff905bf0a as bazel/linkFailureDetector:linkFailureDetector_image
Error parsing reference: "bazel/linkFailureDetector:linkFailureDetector_image" is not a valid repository/tag: invalid reference format: repository name must be lowercase

**Comment by adibrastegarnia** [comment]
It looks like the name of package and the files must be lowercase.

**Comment by xingao267** [comment]
@adibrastegarnia  Yep. The repository name must be lowercase.
