### ISSUE TITLE
Add support for regular docker build with existing Dockerfile

### ISSUE THREAD

**Issue by igorgatis** [bazelbuild/rules_docker#682]
I personally find hard to believe anyone will develop docker images ignoring the power of a regular `Dockerfile`.

Say one needs to build an Docker image based on a existing one (e.g. Ubuntu) or one of build steps is to download a large binary (which you don't want to keep in your source version control).

Bazel has this amazing dependency management mechanism which a `docker build` can take advantage of. For instance, Docker will blindly reuse a layer even if a referenced file changed. Combining bazel tracking and docker, one can fix that.

I extended bazel and came up with the following syntax:
```
load("//tools:docker.bzl", "dockerfile")

dockerfile(
  name = 'samba',
  dockerfile = "Dockerfile",
  repository = "samba",
  srcs = [
    "bin/samba.sh",
    "etc/samba/smb.conf",
  ],
)
```

The rule above takes care of creating a proper temporary context folder which contains only `samba.sh` and `smb.cnf` then calling `docker build`.

This great because I can copy existing Dockerfiles (for security and stability reasons) and have them all under bazel eyes.

My extension suffers from a few inconveniences, like not showing `bazel build` output.

It would be great if this project consider adding support for such rule.

**Comment by nlopezgi** [comment]
Hi @igorgatis,
Thanks for opening this issue.

The main challenge with Dockerfiles + `docker build` is that their execution is both not deterministic and stateful (wrt to how the service caches previous executions). Bazel, as you know, deeply depends on tools being hermetic / deterministic when it comes to executing actions (and also it does not like when tools maintain a state). Specifically, it would be relatively easy to create builds that are not correct, i.e., get to a situation in which 2 users, which run the exact same Bazel build, even from a clean Bazel client end up getting different build outputs / results.

For example, imagine a case in which two users (A and B) have a Dockerfile X that installs package Y using apt-get in its first line after the FROM line. The users create a sample rule like the one you show above in a Bazel project. User A decides to first run Dockerfile X  w/o using Bazel on Monday, docker caches the line that installs package Y. There is an update to packages Y that includes a critical vulnerability fix on Monday night. On tuesday morning, User B builds the Bazel project that includes Dockerfile X. On tuesday morning User A builds the Bazel project as well. For User B, the tests that check that all images are up to date to vulnerabilities are all passing. For user A, they are failing. Even after doing Bazel clean, user A's tests fail. After lots of hacking and opening bugs in rules_docker repo, a rules_docker dev is unable to reproduce the error that User A is getting, and has wasted an entire day. On a hunch, User A actually ends up purging the docker cache, which results in the layer that had installed the faulty version of package Y to be cleared, the tests finally pass. 

If you have any ideas as to how we can use Dockerfiles + `docker build` w/o falling into situations like these, I'll be happy to work with you to design a feature to support them.

Also, note for the specific use cases you mention initially there are viable solutions using these rules that respect the bazel model (+ in some cases the Dockerfile + `docker build` is, imo, problematic):
> Say one needs to build an Docker image based on a existing one (e.g. Ubuntu) 

Just use as base the Ubuntu base image in a container_image, not sure what the issue here is?

>  one of build steps is to download a large binary

Use a workspace rule (e.g., `http_file`) to pull the binary from wherever its stored, you'll be able to check its sha and get a guarantee the built image will always have the correct binary. If you were to use a Dockerfile, you could get a different binary pulled if you ran the Dockerfile yesterday vs today (unless you hardcode a sha check in your Dockerfile).

Please let me know which other cases you are having trouble with so I can help. I understand the appeal of the simplicity of Dockerfiles + `docker build`, but ultimately, this cannot work with Bazel properly w/o breaking the promise at its core: correct Builds.

**Comment by igorgatis** [comment]
Got it. Perhaps a "migration guide" would be really helpfull then.

For auditability reasons, my company requires we keep both the recipe (e.g. Dockerfile) and docker image for every single docker image we use. For instance, we have to have our own `openjdk:8u171-jdk-slim-stretch`. Therefore we copied its Dockerfile, built it and stored the image in our own docker registry.

IIUC, I'd have to translate every line of https://github.com/docker-library/openjdk/blob/c3023e4da10d10e9c9775eabe2d7baac146e7ae1/8/jdk/slim/Dockerfile into BUILD rules. Right? I just have no idea where to start.

On a side note, I'd say that Docker caching is not a problem. We can always pass `--no-cache` or even use Docker in Docker to make sure we're dealing with a fresh environment. At the and of the day, I'd advocate we could use `docker build` to create a tar.gz file that is required to be loaded before running.

**Comment by nlopezgi** [comment]
Yes, you would need to translate your Dockefile to BUILD rules, and this process is not trivial. We're working on providing some examples comparing Dockerfile with equivalent BUILD rules, but they will take some time to land. 
At the 10,000 feet level, what you should do is: start by creating a container_image target that uses debian:stretch as base (use a container_pull target to get debian:stretch), you'll then need a download_pkgs (https://github.com/GoogleContainerTools/base-images-docker/blob/master/package_managers/download_pkgs.bzl) target to get all the apt-get packages you need and a install_packages to install them (https://github.com/GoogleContainerTools/base-images-docker/blob/master/package_managers/install_pkgs.bzl).
You'll then need container_image target(s) that build on the previous ones to add the modified files / symlinks / env vars that you need. You'll probably then need a run_and_commit rule (https://github.com/GoogleContainerTools/base-images-docker/blob/master/util/run.bzl#L225) to run the update-alternatives command. Sorry the process is not trivial, and we do hope to make it easier in the future. 
On the bright side, your audit-process-folks will be very happy to know that you have moved from  Dockerfile that can defines a recipe of how to build but with which you can never know what was actually included in the image, to using an approach in which the build process is actually fully reproducible.

I appreciate your insistence on using Dockerfiles and enabling docker build, but its not something we think we can do while still guaranteeing correctness.

**Comment by igorgatis** [comment]
Thanks @nlopezgi.

**Comment by nlopezgi** [comment]
Hey @igorgatis 
We just submitted a PR that adds an example comparing rules_docker vs Dockerfile (https://github.com/bazelbuild/rules_docker/pull/740). This PR also builds up on a previous PR (https://github.com/bazelbuild/rules_docker/pull/737) that adds an experimental repo rule to create a rules_docker compatible tar from a Dockerfile. This might help with some of your use cases or might make converting your current Dockerfiles to rules_docker simpler. We will probably be adding more complex examples of Dockerfile vs rules_docker in the upcoming weeks.

**Comment by rohansingh** [comment]
@nlopezgi What's the motivation behind those PR's? From what I can tell, #737 is basically doing everything that you warned against in this issue.

Is it safe to use those rules now, or are they just examples?

**Comment by nlopezgi** [comment]
they are just examples for now. And yes, they are not hermetic, implemented as repo rules to reduce the chance of issues, and using the --no_cache docker flag to further try to avoid issues. We acknowledge going from dockerfile to these rules requires these examples to guide non bazel experts.
