### ISSUE TITLE
java_image does not run if base image specified

### ISSUE THREAD

**Issue by nweinthal** [bazelbuild/rules_docker#728]
For some background, I have a java application which runs flawlessly under the default java 8 container.  However, the app needs Java 11, so in my `WORKSPACE` I added:

```
...
container_pull(
  name = "java_11_base",
  registry = "registry.hub.docker.com/library",
  repository = "openjdk",
  tag = "11-slim",
)
...
```

and in my BUILD i have:

```
...
container_image(
    name = "java_11_image",
    base = "@java_11_base//image",
)

java_image(
    name = "server_container",
    srcs = ["Main.java"],
    deps=[
        "@javax_servlet_javax_servlet_api//jar",
        "@jetty_http//jar",
        ...,
    ],
    base = ":java_11_image",
    layers = [":server"],
    main_class = "Main",
)
...
```
If I don't include the `base` argument to `server_container`, it downloads and runs fine with the default java 8 runtime

*What i think should happen* 
running `bazel run //app:server_container` should download and run the java 11 image with my application code

*What actually happens* 
It downloads and builds the image appropriately, and running `docker run -it <image tag>` works just fine.  However, `bazel run` appears to not run the container.

**Comment by nlopezgi** [comment]
hi @nweinthal, thanks for opening this issue. I dont think we have ever tested java_image with java11 (java 11 support is new in bazel iiuc). Probably there needs to be changes in how the image.bzl (https://github.com/bazelbuild/rules_docker/blob/master/java/image.bzl) works with a java11 base. Are you open to dedicate some time to try to get this working? I can help guide you but at this time getting java_image to work with java11 is low on our priority list.

**Comment by nweinthal** [comment]
I can take a stab at it, fwiw the image once built seems to work fine so I imagine it's just some quirk in the run directive.

**Comment by emempi** [comment]
@nweinthal in #739 I was debugging similar issue for python image, the resolution might work for you as well.

**Comment by xingao267** [comment]
I think what happens here is because `legacy_run_behavior` and `docker_run_flags` from `base` [overrides](https://github.com/bazelbuild/rules_docker/blob/master/container/image.bzl#L305) those from the current target as implemented in https://github.com/bazelbuild/rules_docker/pull/505. So is you don't set `legacy_run_behavior` in `container_image` to `False` (which is default to `True`), then it will make other lang_images that use this `container_image` as `base` have its `legacy_run_behavior` set to True, which is probably something we can improve. I'll look into this. During the meantime, you can manually set `legacy_run_behavior` in the `container_image` target to `False` to get around that e.g. https://github.com/bazelbuild/rules_docker/blob/master/testdata/BUILD#L754.

**Comment by akshay-das** [comment]
@surlyengineer Were you able to use custom java base image ?

**Comment by surlyengineer** [comment]
I ultimately was able to, though I did revert back to the default in the end because some of the libraries I was working with weren't updated for Java 11 yet

**Comment by akshay-das** [comment]
@surlyengineer  Could you please share the BUILD configuration added to support custom java base image ?
