### ISSUE TITLE
Language-specific runtime rules

### ISSUE THREAD

**Issue by mattmoor** [bazelbuild/rules_docker#81]
I'm opening this issue to track discussions around the creation of language runtime rules (@dlorenc @sebgoa FYI).

**Comment by sebgoa** [comment]
Might be worth syncing on this next week if you are interested.

Basically we are looking for a way to create a build pipeline in k8s without docker, and publishing to an internal docker registry.

Happy to discuss this somewhere else, since this is a bit out of scope from the general rules_docker repo.

**Comment by mattmoor** [comment]
Yes, I'd definitely like to discuss this further.  Next week is July 4th, so @dlorenc and I are off Monday/Tuesday.  Perhaps Weds or later in the week?

**Comment by sebgoa** [comment]
sure thing. sebgoa@bitnami.com
