### ISSUE TITLE
Cannot build docker tar using container_image rule

### ISSUE THREAD

**Issue by mskonovalov** [bazelbuild/rules_docker#959]
The context:
I have the real bazel project which is quite complicated and set up with `nix` package manager.

To debug my issue I created empty project with only docker rules in it here https://github.com/mskonovalov/bazel-docker-pull-test
I cannot see any issues in the test project, all the commands pass
```
bazel build //services/queue:sqs-mock
bazel build //services/queue:sqs-mock.tar
bazel run //services/queue:sqs-mock
```
even if I switch flags `build --host_force_python=PY2` to `PY3`

But in the real project I see this:
```
bazel build //services/queue:sqs-mock
passed
```

```
bazel run //services/queue:sqs-mock
passed
```

```
bazel build //services/queue:sqs-mock.tar
failed
 File "/.../bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_docker/container/join_layers.runfiles/httplib2/__init__.py", line 28, in <module>
    import email.FeedParser
ModuleNotFoundError: No module named 'email.FeedParser'
Target //services/queue:sqs-mock.tar failed to build
```

which sounds like python2 to python3 issue.

So my question is:
doesn't `bazel run //services/queue:sqs-mock` run `bazel build //services/queue:sqs-mock.tar` inside? And if `run` passes why `build .tar` fails?

Thank you

**Comment by nlopezgi** [comment]
Hi @mskonovalov ,
this sounds quite interesting, particularly since you say this is working fine in your small project with only docker rules.
iirc, `bazel run //services/queue:sqs-mock` does not run `bazel build //services/queue:sqs-mock.tar` inside.
I see you have a relatively complex setup in https://github.com/mskonovalov/bazel-docker-pull-test/blob/master/tools/python/BUILD for your python toolchain. I also see that you are using `incompatible_allow_python_version_transitions`, which I am not familiar with and have never tested with rules_docker.
In any case, your error is most definitely related to the selection of python toolchain, if you are getting the `No module named 'email.FeedParser'` error, then it means the rule tried to run with python3 instead of python2, and afaik, this error means that you did not run with  `host_force_python=PY2`, but frankly, I have no idea how the `incompatible_allow_python_version_transitions` or how this could ever happen.
I'd recommend you ask in [this](https://github.com/bazelbuild/bazel/issues/7899) thread to see if they can help.

**Comment by nlopezgi** [comment]
Is there anything left to resolve here in this repo? Let me know if so to reopen.
