### ISSUE TITLE
add filter / exclude  to docker_build 

### ISSUE THREAD

**Issue by f0** [bazelbuild/rules_docker#96]
At the moment, if you install a deb in debian_build, all content from the deb is extracted.
It would be nice if some filter / exclude option was added to e.g filer /usr/share/man , /usr/share/doc

**Comment by mattmoor** [comment]
tl;dr I think expressing this in the `docker_build` inline would end up being fairly complex.

Since `deb` expansion is really just being done by (a script from) `pkg_tar` anyways, perhaps a better approach would be to have a rule for expanding the `deb` into a filtered `tar`, and then including it into the `docker_build` via `tars`?

@damienmg owns `pkg_tar`, so WDYT?

**Comment by mattmoor** [comment]
In psueudo-code:

```shell
expand_deb(
   name = "foo",
   deb = "bar.deb",
   ... options ...
)

docker_build(
   name = "image",
   tars = [":foo.tar"],
   .... other stuff ...
)
```

**Comment by mattmoor** [comment]
@dlorenc FYI

**Comment by f0** [comment]
@mattmoor yes seems pkg_tar is a better place, thx

btw. is there a IRC / SLACK whatever way to get in contact?

**Comment by mattmoor** [comment]
@damienmg for broader Bazel, I'm not sure this repo rises to the level of its own channel.  Feel free to reach out over email too `<github username>@google.com`.

**Comment by damienmg** [comment]
There is an IRC for Bazel on #bazel @ irc.freenode.net

**Comment by nlopezgi** [comment]
is this still an issue? please reopen if so.
