### ISSUE TITLE
docker_build should have a way to override the default image name

### ISSUE THREAD

**Issue by excavador** [bazelbuild/rules_docker#99]
Please take a look to examples (read README.md)
https://github.com/excavador/docker_bazel_naming_problem/tree/according_documentation
https://github.com/excavador/docker_bazel_naming_problem/tree/another_solution

I do not have any way to specify local docker image repository/name

Also very useless to receive tag-name from target-name (I forced to use target name "latest", not very usefulll)

**Comment by amlinux** [comment]
+1
docker_push rule allows to configure an arbitrary package name, however it doesn't work for the local development workflow, without touching a repository.

**Comment by mattmoor** [comment]
You should check out [this](https://github.com/bazelbuild/rules_docker/blob/master/docker/contrib/with-tag.bzl#L21) variant, which should do what you want (if not, please re-open as I'd like to better understand what you're looking for).

FWIW, the default naming is modeled largely after the `bazel-bin`-style symlink forest.  It is not meant to be directly useful for publishing (which is what it seems you want), but for the naming to be obvious to users.

Right now it lives in `contrib` because I'm a little mixed about naming directly on `docker_build`, I don't like `repository` either, but it snuck by long ago and I'm reluctant to change it now.
